# Generated by Django 6.1 on 2026-09-08 06:16
# ruff: noqa: RUF001

import django.core.validators
import quran_backend.modules.calendar.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        default=quran_backend.modules.calendar.models.event_code,
                        editable=False,
                        help_text="Создаётся автоматически и связывает событие с сайтом и приложением.",
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z][a-z0-9_]*$", "Латинские буквы, цифры и _."
                            )
                        ],
                        verbose_name="Код события",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("occasion", "Значимая дата или период"),
                            ("voluntary_fast", "Напоминание о добровольном посте"),
                            ("no_fast", "Праздник / дни без добровольного поста"),
                        ],
                        default="occasion",
                        max_length=24,
                        verbose_name="Тип отметки",
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Каждый месяц"),
                            (1, "Мухаррам"),
                            (2, "Сафар"),
                            (3, "Раби аль-авваль"),
                            (4, "Раби ас-сани"),
                            (5, "Джумада аль-уля"),
                            (6, "Джумада ас-сания"),
                            (7, "Раджаб"),
                            (8, "Шаабан"),
                            (9, "Рамадан"),
                            (10, "Шавваль"),
                            (11, "Зуль-каада"),
                            (12, "Зуль-хиджа"),
                        ],
                        default=0,
                        verbose_name="Месяц по Хиджре",
                    ),
                ),
                (
                    "day_start",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="С какого числа",
                    ),
                ),
                (
                    "day_end",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Для одного дня укажите то же число. В коротком месяце 30-й день пропускается.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="По какое число включительно",
                    ),
                ),
                (
                    "exclude_ramadan",
                    models.BooleanField(
                        default=False,
                        help_text="Для ежемесячных напоминаний, например белых дней.",
                        verbose_name="Не показывать в Рамадан",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="Название на русском"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="Название на английском"
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="Название на арабском"
                    ),
                ),
                (
                    "title_tr",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="Название на турецком"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, max_length=3000, verbose_name="Пояснение на русском"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, max_length=3000, verbose_name="Пояснение на английском"
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(
                        blank=True, max_length=3000, verbose_name="Пояснение на арабском"
                    ),
                ),
                (
                    "description_tr",
                    models.TextField(
                        blank=True, max_length=3000, verbose_name="Пояснение на турецком"
                    ),
                ),
                (
                    "source_label",
                    models.CharField(blank=True, max_length=180, verbose_name="Название источника"),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="HTTPS-ссылка на подтверждение даты и пояснения. Обязательна для публикации.",
                        verbose_name="Ссылка на источник",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Для публикации заполните все четыре перевода и источник. Обновление каталога — до 5 минут онлайн.",
                        verbose_name="Показывать на сайте и в приложении",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=100, verbose_name="Порядок в списке"),
                ),
            ],
            options={
                "verbose_name": "событие календаря",
                "verbose_name_plural": "События календаря",
                "ordering": ("sort_order", "code"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("month__lte", 12)), name="calendar_month_range"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("day_end__gte", models.F("day_start")),
                            ("day_end__lte", 30),
                            ("day_start__gte", 1),
                        ),
                        name="calendar_day_range",
                    ),
                ],
            },
        ),
    ]
