# Generated by Django 6.0.8 on 2026-08-08 22:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ayah",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveSmallIntegerField()),
                ("text_uthmani", models.TextField()),
                ("text_search", models.TextField(blank=True)),
                ("juz_number", models.PositiveSmallIntegerField()),
            ],
            options={
                "db_table": "quran_ayah",
                "ordering": ["surah__number", "number"],
            },
        ),
        migrations.CreateModel(
            name="QuranEdition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name_ar", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255)),
                ("name_ru", models.CharField(max_length=255)),
                ("riwayah", models.CharField(max_length=128)),
                ("source_name", models.CharField(max_length=255)),
                ("source_url", models.URLField(blank=True)),
                ("license_name", models.CharField(max_length=255)),
                ("license_url", models.URLField(blank=True)),
            ],
            options={
                "db_table": "quran_edition",
            },
        ),
        migrations.CreateModel(
            name="QuranEditionVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=64)),
                ("checksum_sha256", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("page_count", models.PositiveSmallIntegerField(default=604)),
                ("surah_count", models.PositiveSmallIntegerField(default=114)),
                ("juz_count", models.PositiveSmallIntegerField(default=30)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="quran.quranedition",
                    ),
                ),
            ],
            options={
                "db_table": "quran_edition_version",
            },
        ),
        migrations.AddField(
            model_name="quranedition",
            name="active_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_editions",
                to="quran.quraneditionversion",
            ),
        ),
        migrations.CreateModel(
            name="MushafPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveSmallIntegerField()),
                ("image_width", models.PositiveIntegerField()),
                ("image_height", models.PositiveIntegerField()),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("asset_variants", models.JSONField(default=list)),
                (
                    "edition_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pages",
                        to="quran.quraneditionversion",
                    ),
                ),
            ],
            options={
                "db_table": "quran_mushaf_page",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Juz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveSmallIntegerField()),
                (
                    "end_ayah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="juz_ends",
                        to="quran.ayah",
                    ),
                ),
                (
                    "start_ayah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="juz_starts",
                        to="quran.ayah",
                    ),
                ),
                (
                    "edition_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="juz",
                        to="quran.quraneditionversion",
                    ),
                ),
            ],
            options={
                "db_table": "quran_juz",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="SourceManifest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_version", models.CharField(max_length=128)),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("expected_surahs", models.PositiveSmallIntegerField()),
                ("expected_ayahs", models.PositiveIntegerField()),
                ("expected_pages", models.PositiveSmallIntegerField()),
                ("payload", models.JSONField(default=dict)),
                ("imported_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "edition_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manifests",
                        to="quran.quraneditionversion",
                    ),
                ),
            ],
            options={
                "db_table": "quran_source_manifest",
            },
        ),
        migrations.CreateModel(
            name="Surah",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveSmallIntegerField()),
                ("name_ar", models.CharField(max_length=128)),
                ("name_en", models.CharField(max_length=128)),
                ("name_ru", models.CharField(max_length=128)),
                (
                    "revelation_type",
                    models.CharField(
                        choices=[("meccan", "Meccan"), ("medinan", "Medinan")], max_length=16
                    ),
                ),
                ("ayah_count", models.PositiveSmallIntegerField()),
                (
                    "edition_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surahs",
                        to="quran.quraneditionversion",
                    ),
                ),
            ],
            options={
                "db_table": "quran_surah",
                "ordering": ["number"],
            },
        ),
        migrations.AddField(
            model_name="ayah",
            name="surah",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="ayahs", to="quran.surah"
            ),
        ),
        migrations.CreateModel(
            name="AyahPageRegion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reading_order", models.PositiveSmallIntegerField()),
                ("polygon", models.JSONField(default=list)),
                ("x", models.DecimalField(decimal_places=7, max_digits=8)),
                ("y", models.DecimalField(decimal_places=7, max_digits=8)),
                ("width", models.DecimalField(decimal_places=7, max_digits=8)),
                ("height", models.DecimalField(decimal_places=7, max_digits=8)),
                (
                    "ayah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="page_regions",
                        to="quran.ayah",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="quran.mushafpage",
                    ),
                ),
            ],
            options={
                "db_table": "quran_ayah_page_region",
                "ordering": ["reading_order"],
                "indexes": [models.Index(fields=["ayah", "page"], name="quran_region_ayah_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("page", "ayah", "reading_order"),
                        name="quran_region_page_ayah_order_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("x__gte", 0), ("x__lte", 1)),
                        name="quran_region_x_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("y__gte", 0), ("y__lte", 1)),
                        name="quran_region_y_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("width__gt", 0), ("width__lte", 1)),
                        name="quran_region_width_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("height__gt", 0), ("height__lte", 1)),
                        name="quran_region_height_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("x__lte", 1), ("width__lte", 1)),
                        name="quran_region_bbox_values_lte_one",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="quraneditionversion",
            index=models.Index(fields=["status", "edition"], name="quran_version_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="quraneditionversion",
            constraint=models.UniqueConstraint(
                fields=("edition", "version"), name="quran_edition_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="quraneditionversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("page_count__gt", 0)), name="quran_version_positive_pages"
            ),
        ),
        migrations.AddConstraint(
            model_name="quraneditionversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("surah_count__gt", 0)), name="quran_version_positive_surahs"
            ),
        ),
        migrations.AddConstraint(
            model_name="quraneditionversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("juz_count__gt", 0)), name="quran_version_positive_juz"
            ),
        ),
        migrations.AddConstraint(
            model_name="quraneditionversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("published_at__isnull", False), ("status", "published")),
                    models.Q(("status", "published"), _negated=True),
                    _connector="OR",
                ),
                name="quran_published_version_has_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="mushafpage",
            constraint=models.UniqueConstraint(
                fields=("edition_version", "number"), name="quran_page_version_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="mushafpage",
            constraint=models.CheckConstraint(
                condition=models.Q(("number__gte", 1), ("number__lte", 604)),
                name="quran_page_number_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="mushafpage",
            constraint=models.CheckConstraint(
                condition=models.Q(("image_height__gt", 0), ("image_width__gt", 0)),
                name="quran_page_positive_dimensions",
            ),
        ),
        migrations.AddConstraint(
            model_name="juz",
            constraint=models.UniqueConstraint(
                fields=("edition_version", "number"), name="quran_juz_version_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="juz",
            constraint=models.CheckConstraint(
                condition=models.Q(("number__gte", 1), ("number__lte", 30)),
                name="quran_juz_number_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcemanifest",
            constraint=models.UniqueConstraint(
                fields=("edition_version", "source_version"),
                name="quran_manifest_source_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="surah",
            constraint=models.UniqueConstraint(
                fields=("edition_version", "number"), name="quran_surah_version_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="surah",
            constraint=models.CheckConstraint(
                condition=models.Q(("number__gte", 1), ("number__lte", 114)),
                name="quran_surah_number_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="surah",
            constraint=models.CheckConstraint(
                condition=models.Q(("ayah_count__gt", 0)), name="quran_surah_positive_ayah_count"
            ),
        ),
        migrations.AddIndex(
            model_name="ayah",
            index=models.Index(fields=["juz_number", "surah", "number"], name="quran_ayah_juz_idx"),
        ),
        migrations.AddConstraint(
            model_name="ayah",
            constraint=models.UniqueConstraint(
                fields=("surah", "number"), name="quran_ayah_surah_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="ayah",
            constraint=models.CheckConstraint(
                condition=models.Q(("number__gte", 1)), name="quran_ayah_positive_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="ayah",
            constraint=models.CheckConstraint(
                condition=models.Q(("juz_number__gte", 1), ("juz_number__lte", 30)),
                name="quran_ayah_juz_range",
            ),
        ),
    ]
