# Generated by Django 6.1 on 2026-08-23 14:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quran", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hizb",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveSmallIntegerField()),
            ],
            options={
                "db_table": "quran_hizb",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="RubElHizb",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveSmallIntegerField()),
            ],
            options={
                "db_table": "quran_rub_el_hizb",
                "ordering": ["number"],
            },
        ),
        migrations.AddField(
            model_name="ayah",
            name="hizb_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ayah",
            name="rub_el_hizb_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quraneditionversion",
            name="hizb_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quraneditionversion",
            name="rub_el_hizb_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="ayah",
            index=models.Index(
                fields=["hizb_number", "surah", "number"], name="quran_ayah_hizb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ayah",
            index=models.Index(
                fields=["rub_el_hizb_number", "surah", "number"], name="quran_ayah_rub_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ayah",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("hizb_number__isnull", True),
                    models.Q(("hizb_number__gte", 1), ("hizb_number__lte", 60)),
                    _connector="OR",
                ),
                name="quran_ayah_hizb_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="ayah",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rub_el_hizb_number__isnull", True),
                    models.Q(("rub_el_hizb_number__gte", 1), ("rub_el_hizb_number__lte", 240)),
                    _connector="OR",
                ),
                name="quran_ayah_rub_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="quraneditionversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("hizb_count__gte", 0), ("hizb_count__lte", 60)),
                name="quran_version_hizb_count_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="quraneditionversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("rub_el_hizb_count__gte", 0), ("rub_el_hizb_count__lte", 240)),
                name="quran_version_rub_count_range",
            ),
        ),
        migrations.AddField(
            model_name="hizb",
            name="edition_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hizb",
                to="quran.quraneditionversion",
            ),
        ),
        migrations.AddField(
            model_name="hizb",
            name="end_ayah",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hizb_ends",
                to="quran.ayah",
            ),
        ),
        migrations.AddField(
            model_name="hizb",
            name="start_ayah",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hizb_starts",
                to="quran.ayah",
            ),
        ),
        migrations.AddField(
            model_name="rubelhizb",
            name="edition_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rub_el_hizb",
                to="quran.quraneditionversion",
            ),
        ),
        migrations.AddField(
            model_name="rubelhizb",
            name="end_ayah",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rub_ends",
                to="quran.ayah",
            ),
        ),
        migrations.AddField(
            model_name="rubelhizb",
            name="hizb",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quarters",
                to="quran.hizb",
            ),
        ),
        migrations.AddField(
            model_name="rubelhizb",
            name="start_ayah",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rub_starts",
                to="quran.ayah",
            ),
        ),
        migrations.AddConstraint(
            model_name="hizb",
            constraint=models.UniqueConstraint(
                fields=("edition_version", "number"), name="quran_hizb_version_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="hizb",
            constraint=models.CheckConstraint(
                condition=models.Q(("number__gte", 1), ("number__lte", 60)),
                name="quran_hizb_number_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="rubelhizb",
            constraint=models.UniqueConstraint(
                fields=("edition_version", "number"), name="quran_rub_version_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="rubelhizb",
            constraint=models.CheckConstraint(
                condition=models.Q(("number__gte", 1), ("number__lte", 240)),
                name="quran_rub_number_range",
            ),
        ),
    ]
