# Generated by Django 6.1 on 2026-08-25 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quran", "0002_add_hizb_navigation"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuranFoundationMushaf",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("environment", models.CharField(max_length=16)),
                ("source_id", models.PositiveIntegerField()),
                ("resource_content_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("qirat_id", models.PositiveIntegerField(blank=True, null=True)),
                ("qirat_name", models.CharField(max_length=128)),
                ("pages_count", models.PositiveSmallIntegerField()),
                ("lines_per_page", models.PositiveSmallIntegerField()),
                ("default_font_name", models.CharField(max_length=128)),
                ("mapping_mode", models.CharField(max_length=64)),
                ("schema_version", models.CharField(max_length=32)),
                ("sync_sequence", models.PositiveBigIntegerField()),
                ("source_checksum_sha256", models.CharField(max_length=64)),
                ("is_available", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField()),
            ],
            options={
                "db_table": "quran_qf_mushaf",
                "ordering": ["source_id"],
                "indexes": [
                    models.Index(
                        fields=["environment", "is_available", "source_id"],
                        name="quran_qf_mushaf_public_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("environment", "source_id"), name="quran_qf_mushaf_source_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("environment__in", ["prelive", "production"])),
                        name="quran_qf_mushaf_env_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("pages_count__gt", 0)),
                        name="quran_qf_mushaf_pages_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("lines_per_page__gt", 0)),
                        name="quran_qf_mushaf_lines_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuranFoundationMushafSyncState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("environment", models.CharField(max_length=16)),
                ("resources_filter", models.CharField(default="mushafs:*", max_length=128)),
                ("sync_token", models.TextField(blank=True)),
                ("last_sync_sequence", models.PositiveBigIntegerField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "db_table": "quran_qf_mushaf_sync_state",
                "ordering": ["environment", "resources_filter"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("environment", "resources_filter"),
                        name="quran_qf_mushaf_sync_filter_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("environment__in", ["prelive", "production"])),
                        name="quran_qf_mushaf_sync_env_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuranFoundationMushafPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_id", models.PositiveBigIntegerField()),
                ("page_number", models.PositiveSmallIntegerField()),
                ("verse_mapping", models.JSONField(default=dict)),
                ("first_verse_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("last_verse_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("first_word_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("last_word_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("verses_count", models.PositiveSmallIntegerField()),
                ("words", models.JSONField(default=list)),
                (
                    "mushaf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cached_pages",
                        to="quran.quranfoundationmushaf",
                    ),
                ),
            ],
            options={
                "db_table": "quran_qf_mushaf_page",
                "ordering": ["page_number"],
                "indexes": [
                    models.Index(fields=["mushaf", "page_number"], name="quran_qf_page_lookup_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mushaf", "page_number"), name="quran_qf_mushaf_page_number_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("page_number__gt", 0)),
                        name="quran_qf_mushaf_page_positive",
                    ),
                ],
            },
        ),
    ]
