# Generated by Django 6.1 on 2026-09-07 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0004_quranfoundationnativepublication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MushafRendition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код оформления')),
                ('names', models.JSONField(default=dict, verbose_name='Названия на языках приложения')),
            ],
            options={
                'verbose_name': 'оформление Мусхафа',
                'verbose_name_plural': 'Оформления Мусхафа',
                'db_table': 'quran_mushaf_rendition',
            },
        ),
        migrations.CreateModel(
            name='MushafRenditionRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=64, verbose_name='Версия набора')),
                ('checksum_sha256', models.CharField(max_length=64, verbose_name='SHA-256 полного набора')),
                ('source_commit', models.CharField(max_length=40, verbose_name='Commit источника')),
                ('source_url', models.URLField(verbose_name='Источник страниц')),
                ('renderer', models.CharField(max_length=64, verbose_name='Версия раскладки')),
                ('widths', models.JSONField(default=list, verbose_name='Разрешения страниц')),
                ('page_count', models.PositiveSmallIntegerField(default=604, verbose_name='Количество страниц')),
                ('staging_only', models.BooleanField(default=True, verbose_name='Только тестовый сервер')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Подключено')),
                ('canonical_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quran.quraneditionversion', verbose_name='Канонические аяты (не изменяются)')),
                ('rendition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='quran.mushafrendition')),
            ],
            options={
                'verbose_name': 'версия оформления Мусхафа',
                'verbose_name_plural': 'Версии оформления Мусхафа',
                'db_table': 'quran_mushaf_rendition_release',
            },
        ),
        migrations.CreateModel(
            name='MushafRenditionPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер страницы')),
                ('image_width', models.PositiveIntegerField(verbose_name='Ширина исходной раскладки')),
                ('image_height', models.PositiveIntegerField(verbose_name='Высота исходной раскладки')),
                ('checksum_sha256', models.CharField(max_length=64, verbose_name='SHA-256 карты страницы')),
                ('assets', models.JSONField(default=list, verbose_name='Проверенные изображения')),
                ('regions', models.JSONField(default=list, verbose_name='Области аятов')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='quran.mushafrenditionrelease')),
            ],
            options={
                'verbose_name': 'страница оформления Мусхафа',
                'verbose_name_plural': 'Страницы оформления Мусхафа',
                'db_table': 'quran_mushaf_rendition_page',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='mushafrendition',
            name='active_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_for', to='quran.mushafrenditionrelease', verbose_name='Доступная версия страниц'),
        ),
        migrations.AddConstraint(
            model_name='mushafrenditionrelease',
            constraint=models.UniqueConstraint(fields=('rendition', 'version'), name='quran_rendition_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='mushafrenditionpage',
            constraint=models.UniqueConstraint(fields=('release', 'number'), name='quran_rendition_page_unique'),
        ),
        migrations.AddConstraint(
            model_name='mushafrenditionpage',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 604)), name='quran_rendition_page_range'),
        ),
    ]
