# Generated by Django 6.1 on 2026-09-12 22:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_page_mappings(apps, schema_editor):
    region = apps.get_model("quran", "AyahPageRegion")
    mapping = apps.get_model("quran", "AyahPageMapping")
    alias = schema_editor.connection.alias
    pairs = region.objects.using(alias).order_by().values_list("page_id", "ayah_id").distinct()
    pending = []
    for page_id, ayah_id in pairs.iterator(chunk_size=1000):
        pending.append(mapping(page_id=page_id, ayah_id=ayah_id))
        if len(pending) == 1000:
            mapping.objects.using(alias).bulk_create(pending, ignore_conflicts=True)
            pending = []
    mapping.objects.using(alias).bulk_create(pending, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("quran", "0006_rendition_source_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mushafpage",
            name="asset_variants",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="mushafpage",
            name="checksum_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="mushafpage",
            name="image_height",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="mushafpage",
            name="image_width",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="AyahPageMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ayah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="page_mappings",
                        to="quran.ayah",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ayah_mappings",
                        to="quran.mushafpage",
                    ),
                ),
            ],
            options={
                "db_table": "quran_ayah_page_mapping",
                "constraints": [
                    models.UniqueConstraint(fields=("page", "ayah"), name="quran_page_ayah_unique")
                ],
            },
        ),
        migrations.RunPython(copy_page_mappings, migrations.RunPython.noop),
    ]
