# Generated by Django 6.0.8 on 2026-08-08 22:02

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import quran_backend.modules.accounts.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("guest", "Guest"),
                            ("active", "Active"),
                            ("pending_deletion", "Pending deletion"),
                            ("suspended", "Suspended"),
                            ("deleted", "Deleted"),
                        ],
                        default="guest",
                        max_length=24,
                    ),
                ),
                ("preferred_locale", models.CharField(default="en", max_length=8)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_user",
            },
            managers=[
                ("objects", quran_backend.modules.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuthIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("google", "Google"),
                            ("apple", "Apple"),
                            ("telegram", "Telegram"),
                        ],
                        max_length=16,
                    ),
                ),
                ("provider_subject", models.CharField(max_length=255)),
                ("email_at_provider", models.EmailField(blank=True, max_length=254, null=True)),
                ("email_verified", models.BooleanField(default=False)),
                ("linked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_auth_identity",
            },
        ),
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("product_analytics", "Product analytics"),
                            ("notifications", "Notifications"),
                            ("diagnostics", "Diagnostics"),
                            ("location_storage", "Location storage"),
                        ],
                        max_length=32,
                    ),
                ),
                ("policy_version", models.CharField(max_length=32)),
                ("granted_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_consent",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web"),
                            ("telegram", "Telegram"),
                        ],
                        max_length=16,
                    ),
                ),
                ("installation_id_hash", models.CharField(max_length=64)),
                (
                    "installation_credential_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("bootstrap_generation", models.PositiveBigIntegerField(default=0)),
                ("app_version", models.CharField(blank=True, max_length=32)),
                ("locale", models.CharField(default="en", max_length=8)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_device",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["status", "created_at"], name="accounts_user_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("email__isnull", False)),
                name="accounts_user_email_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("preferred_locale__in", ["ar", "en", "ru"])),
                name="accounts_user_supported_locale",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "active"), _negated=True),
                    ("email__isnull", False),
                    _connector="OR",
                ),
                name="accounts_active_user_has_email",
            ),
        ),
        migrations.AddIndex(
            model_name="authidentity",
            index=models.Index(fields=["user", "provider"], name="accounts_identity_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="authidentity",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_subject"),
                name="accounts_identity_provider_subject_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="consent",
            constraint=models.UniqueConstraint(
                fields=("user", "purpose", "policy_version"),
                name="accounts_consent_user_purpose_policy_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="consent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("granted_at__isnull", False), ("withdrawn_at__isnull", True)),
                    models.Q(("granted_at__isnull", False), ("withdrawn_at__isnull", False)),
                    _connector="OR",
                ),
                name="accounts_consent_has_grant",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["user", "last_seen_at"], name="accounts_device_seen_idx"),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                fields=("user", "installation_id_hash"),
                name="accounts_device_user_installation_unique",
            ),
        ),
    ]
