# Generated by Django 6.0.8 on 2026-08-09 03:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("compromise_detected_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "accounts_refresh_session",
            },
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("secret_hash", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "accounts_refresh_token",
            },
        ),
        migrations.RemoveConstraint(
            model_name="device",
            name="accounts_device_user_installation_unique",
        ),
        migrations.AlterField(
            model_name="device",
            name="installation_id_hash",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(("locale__in", ["ar", "en", "ru"])),
                name="accounts_device_supported_locale",
            ),
        ),
        migrations.AddField(
            model_name="refreshsession",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refresh_sessions",
                to="accounts.device",
            ),
        ),
        migrations.AddField(
            model_name="refreshsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refresh_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="replaced_by",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaces",
                to="accounts.refreshtoken",
            ),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tokens",
                to="accounts.refreshsession",
            ),
        ),
        migrations.AddIndex(
            model_name="refreshsession",
            index=models.Index(
                fields=["device", "revoked_at", "expires_at"], name="accounts_session_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refreshsession",
            index=models.Index(fields=["user", "created_at"], name="accounts_session_user_idx"),
        ),
        migrations.AddIndex(
            model_name="refreshsession",
            index=models.Index(fields=["expires_at"], name="accounts_session_expiry_idx"),
        ),
        migrations.AddIndex(
            model_name="refreshsession",
            index=models.Index(fields=["revoked_at"], name="accounts_session_revoked_idx"),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(fields=["session", "created_at"], name="accounts_token_session_idx"),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["expires_at", "revoked_at"], name="accounts_token_expiry_idx"
            ),
        ),
    ]
