# Generated by Django 6.1 on 2026-08-23 15:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_refresh_sessions"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAuthChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                ("code_hash", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("attempts_remaining", models.PositiveSmallIntegerField(default=5)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("verification_key", models.UUIDField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="email_auth_challenges",
                        to="accounts.device",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="email_auth_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "result_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completed_email_auth_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_email_auth_challenge",
                "indexes": [
                    models.Index(fields=["device", "created_at"], name="accounts_email_device_idx"),
                    models.Index(fields=["expires_at"], name="accounts_email_expiry_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("attempts_remaining__lte", 10)),
                        name="accounts_email_attempts_bounded",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("consumed_at__isnull", True),
                                ("result_user__isnull", True),
                                ("verification_key__isnull", True),
                            ),
                            models.Q(
                                ("consumed_at__isnull", False),
                                ("result_user__isnull", False),
                                ("verification_key__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="accounts_email_challenge_result_shape",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GuestMergeAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("idempotency_key", models.UUIDField(unique=True)),
                ("moved_counts", models.JSONField(default=dict)),
                ("completed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "source_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_merge_source_audit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_merge_target_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trigger_identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_merge_audits",
                        to="accounts.authidentity",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_guest_merge_audit",
                "indexes": [
                    models.Index(
                        fields=["target_user", "completed_at"], name="accounts_merge_target_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("source_user", models.F("target_user")), _negated=True),
                        name="accounts_guest_merge_distinct_users",
                    )
                ],
            },
        ),
    ]
