# Generated by Django 6.1 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0002_usersynccursor_minimum_valid_cursor"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="syncoperation",
            index=models.Index(
                fields=["user", "entity_type", "entity_id"],
                name="reading_sync_op_entity_idx",
            ),
        ),
    ]
