# Generated by Django 6.1 on 2026-08-09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0003_syncoperation_entity_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetiredBookmarkId",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bookmark_id", models.UUIDField()),
                ("last_revision", models.PositiveBigIntegerField()),
                ("retired_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retired_bookmark_ids",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reading_retired_bookmark_id",
                "indexes": [
                    models.Index(
                        fields=["user", "retired_at"],
                        name="reading_retired_bm_time_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "bookmark_id"),
                        name="reading_retired_bookmark_user_id_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("last_revision__gte", 1)),
                        name="reading_retired_bookmark_revision_positive",
                    ),
                ],
            },
        ),
    ]
