# Generated by Django 6.1 on 2026-08-28 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_support_turkish_locale"),
        ("reading", "0008_flexible_prayer_reading_pages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuranReaderPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locale", models.CharField(max_length=8)),
                ("translation_enabled", models.BooleanField(default=False)),
                ("translation_source_id", models.PositiveIntegerField(blank=True, null=True)),
                ("tafsir_enabled", models.BooleanField(default=False)),
                ("tafsir_source_id", models.PositiveIntegerField(blank=True, null=True)),
                ("client_updated_at", models.DateTimeField()),
                ("revision", models.PositiveBigIntegerField(default=1)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quran_reader_preferences",
                        to="accounts.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quran_reader_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "quran_reader_preference",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "locale"), name="quran_reader_preference_user_locale_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("locale__in", ["ar", "en", "ru", "tr"])),
                        name="quran_reader_preference_supported_locale",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("revision__gte", 1)),
                        name="quran_reader_preference_revision_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("translation_enabled", False),
                            ("translation_source_id__isnull", False),
                            _connector="OR",
                        ),
                        name="quran_reader_preference_translation_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("tafsir_enabled", False),
                            ("tafsir_source_id__isnull", False),
                            _connector="OR",
                        ),
                        name="quran_reader_preference_tafsir_shape",
                    ),
                ],
            },
        ),
    ]
