# Generated by Django 6.1 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0009_quranreaderpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayerreadingplan",
            name="notifications_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
