"use client";

import { IconButton, ProgressBar, Screen, Toggle, TopBar } from "../components";
import { alFatihaAyahs, prayerTimes, reciters } from "../data";
import { Icon } from "../icons";
import { l, number } from "../i18n";
import { usePrototype } from "../store";
import type { PrayerCode } from "../types";

export function PlanScreen() {
  const { state, setState, navigate, notify } = usePrototype();
  const locale = state.locale;
  const totalPrayerPages = Object.values(state.prayerPages).reduce((sum, value) => sum + value, 0);
  const completion = Math.min(100, Math.round((state.dailyAchieved / state.dailyTarget) * 100));
  return (
    <Screen className="plan-screen">
      <TopBar title={l(locale, { ru: "Мой план", en: "My plan", ar: "خطتي", tr: "Planım" })} subtitle={l(locale, { ru: "Регулярность без давления", en: "Consistency without pressure", ar: "استمرارية بلا ضغط", tr: "Baskı olmadan düzen" })} action={<IconButton label="Plan settings" onClick={() => navigate("settings")}><Icon name="settings"/></IconButton>} />
      <section className="plan-hero">
        <div className="plan-hero-top"><div><span className="eyebrow light">{l(locale, { ru: "Сегодня", en: "Today", ar: "اليوم", tr: "Bugün" })}</span><h1>{number(locale, state.dailyAchieved)} <small>/ {number(locale, state.dailyTarget)} {l(locale, { ru: "страниц", en: "pages", ar: "صفحات", tr: "sayfa" })}</small></h1></div><div className="plan-percent">{number(locale, completion)}%</div></div>
        <ProgressBar value={state.dailyAchieved} max={state.dailyTarget}/>
        <p>{l(locale, { ru: "Любое чтение считается. Пропуски не переносятся в долг.", en: "Every bit counts. Missed days never turn into debt.", ar: "كل قراءة تُحتسب، والأيام الفائتة لا تتحول إلى دَين.", tr: "Her okuma sayılır. Kaçırılan günler borca dönüşmez." })}</p>
      </section>
      <section className="plan-stats">
        <div><span className="stat-icon"><Icon name="flame"/></span><strong>{number(locale, 8)}</strong><small>{l(locale, { ru: "дней подряд", en: "day streak", ar: "أيام متتالية", tr: "gün seri" })}</small></div>
        <div><span className="stat-icon"><Icon name="calendar"/></span><strong>{number(locale, 21)}</strong><small>{l(locale, { ru: "день в месяце", en: "days this month", ar: "يومًا هذا الشهر", tr: "bu ay gün" })}</small></div>
        <div><span className="stat-icon"><Icon name="book"/></span><strong>{number(locale, 74)}</strong><small>{l(locale, { ru: "страницы всего", en: "pages total", ar: "صفحة إجمالًا", tr: "toplam sayfa" })}</small></div>
      </section>
      <section className="section-block plan-cards">
        <div className="section-heading"><div><span className="eyebrow">{l(locale, { ru: "Центр планирования", en: "Planning hub", ar: "مركز التخطيط", tr: "Planlama merkezi" })}</span><h2>{l(locale, { ru: "Ваши практики", en: "Your practices", ar: "ممارساتك", tr: "Pratikleriniz" })}</h2></div></div>
        <button className="plan-feature-row" onClick={() => navigate("prayer-reading")}><span className="list-icon sand"><Icon name="clock"/></span><span><strong>{l(locale, { ru: "Чтение после намаза", en: "Reading after prayer", ar: "القراءة بعد الصلاة", tr: "Namaz sonrası okuma" })}</strong><small>{number(locale, totalPrayerPages)} / {number(locale, 10)} {l(locale, { ru: "страниц сегодня", en: "pages today", ar: "صفحات اليوم", tr: "sayfa bugün" })}</small></span><ProgressBar value={totalPrayerPages} max={10}/><Icon name="chevron"/></button>
        <button className="plan-feature-row" onClick={() => navigate("memorization")}><span className="list-icon green"><Icon name="repeat"/></span><span><strong>{l(locale, { ru: "Заучивание", en: "Memorization", ar: "الحفظ", tr: "Ezber" })}</strong><small>{locale === "ar" ? "الفاتحة ١–٣" : "Аль-Фатиха 1–3"}</small></span><ProgressBar value={state.memorization.completedRepetitions} max={state.memorization.targetRepetitions}/><Icon name="chevron"/></button>
        <button className="plan-feature-row" onClick={() => navigate("prayer")}><span className="list-icon blue"><Icon name="bell"/></span><span><strong>{l(locale, { ru: "Уведомления", en: "Notifications", ar: "الإشعارات", tr: "Bildirimler" })}</strong><small>{Object.values(state.prayerNotifications).filter(Boolean).length} {l(locale, { ru: "включено", en: "enabled", ar: "مفعلة", tr: "etkin" })}</small></span><span className="mini-state">{state.afterPrayerPrompt ? l(locale, { ru: "+ чтение", en: "+ reading", ar: "+ القراءة", tr: "+ okuma" }) : l(locale, { ru: "Настроить", en: "Set up", ar: "إعداد", tr: "Ayarla" })}</span><Icon name="chevron"/></button>
      </section>
      <section className="history-card">
        <div className="section-heading"><div><span className="eyebrow">{l(locale, { ru: "История", en: "History", ar: "السجل", tr: "Geçmiş" })}</span><h2>{l(locale, { ru: "Последние 7 дней", en: "Last 7 days", ar: "آخر ٧ أيام", tr: "Son 7 gün" })}</h2></div><div className="range-pills"><button className="is-active">7</button><button>30</button><button>90</button></div></div>
        <div className="week-chart">{[3,6,4,0,8,5,state.dailyAchieved].map((value, index) => <div key={index}><span className={index === 6 ? "is-today" : ""} style={{ height: `${Math.max(8, value * 8)}%` }}/><small>{["Пн","Вт","Ср","Чт","Пт","Сб","Вс"][index]}</small></div>)}</div>
        <div className="history-entry"><span className="list-icon green"><Icon name="book"/></span><span><strong>{l(locale, { ru: "Автоматическое чтение", en: "Automatic reading", ar: "قراءة تلقائية", tr: "Otomatik okuma" })}</strong><small>{l(locale, { ru: "Сегодня · 08:14", en: "Today · 08:14", ar: "اليوم · ٠٨:١٤", tr: "Bugün · 08:14" })}</small></span><strong>2 {l(locale, { ru: "стр.", en: "pp.", ar: "ص", tr: "sf." })}</strong></div>
        <div className="history-entry"><span className="list-icon sand"><Icon name="edit"/></span><span><strong>{l(locale, { ru: "Добавлено вручную", en: "Added manually", ar: "أُضيف يدويًا", tr: "Elle eklendi" })}</strong><small>{l(locale, { ru: "Вчера · 21:02", en: "Yesterday · 21:02", ar: "أمس · ٢١:٠٢", tr: "Dün · 21:02" })}</small></span><span className="entry-actions"><IconButton label="Edit"><Icon name="edit" size={17}/></IconButton><IconButton label="Delete"><Icon name="trash" size={17}/></IconButton></span></div>
        <button className="button secondary wide" onClick={() => {
          setState((current) => ({ ...current, dailyAchieved: current.dailyAchieved + 1 }));
          notify(l(locale, { ru: "Добавлена 1 страница", en: "Added 1 page", ar: "أُضيفت صفحة واحدة", tr: "1 sayfa eklendi" }));
        }}><Icon name="plus" />{l(locale, { ru: "Добавить чтение вручную", en: "Add reading manually", ar: "إضافة قراءة يدويًا", tr: "Okumayı elle ekle" })}</button>
      </section>
    </Screen>
  );
}

export function PrayerReadingScreen() {
  const { state, setState, notify } = usePrototype();
  const locale = state.locale;
  const total = Object.values(state.prayerPages).reduce((sum, value) => sum + value, 0);
  const addPages = (code: PrayerCode, amount: number) => {
    setState((current) => ({ ...current, dailyAchieved: current.dailyAchieved + amount, prayerPages: { ...current.prayerPages, [code]: current.prayerPages[code] + amount } }));
    notify(l(locale, { ru: `${amount} страницы учтены в общем прогрессе`, en: `${amount} pages added to today’s progress`, ar: `أُضيفت ${number(locale, amount)} صفحات إلى تقدم اليوم`, tr: `${amount} sayfa bugünkü ilerlemeye eklendi` }));
  };
  return (
    <Screen className="prayer-reading-screen">
      <TopBar back title={l(locale, { ru: "Чтение после намаза", en: "Reading after prayer", ar: "القراءة بعد الصلاة", tr: "Namaz sonrası okuma" })} subtitle={l(locale, { ru: "Пять независимых шагов", en: "Five independent moments", ar: "خمس لحظات مستقلة", tr: "Beş bağımsız an" })}/>
      <section className="prayer-reading-summary"><div><span className="eyebrow light">{l(locale, { ru: "Сегодня", en: "Today", ar: "اليوم", tr: "Bugün" })}</span><h1>{number(locale, total)} <small>/ {number(locale, 10)} {l(locale, { ru: "страниц", en: "pages", ar: "صفحات", tr: "sayfa" })}</small></h1></div><div className="page-stack" aria-hidden="true"><i/><i/><i/></div><ProgressBar value={total} max={10}/><p>{l(locale, { ru: "Если прочитаете больше цели, всё попадёт в фактический прогресс. Пропуск не создаёт долг.", en: "Extra pages count toward actual progress. Skipping never creates debt.", ar: "الصفحات الزائدة تُحتسب في التقدم الفعلي، والتخطي لا ينشئ دَينًا.", tr: "Fazladan sayfalar gerçek ilerlemeye sayılır. Atlamak borç oluşturmaz." })}</p></section>
      <div className="prayer-page-list">{prayerTimes.map((prayer, index) => {
        const actual = state.prayerPages[prayer.code];
        const target = 2;
        return <article key={prayer.code} className={actual >= target ? "is-complete" : ""}><div className="prayer-row-head"><span className="prayer-index">{number(locale, index + 1)}</span><span><strong>{prayer[locale]}</strong><small>{prayer.ar} · {prayer.time}</small></span>{actual >= target ? <span className="complete-mark"><Icon name="check"/></span> : <button className="button small" onClick={() => addPages(prayer.code, 2)}>{l(locale, { ru: "+ 2 стр.", en: "+ 2 pages", ar: "+ صفحتان", tr: "+ 2 sayfa" })}</button>}</div><div className="prayer-page-progress"><span>{l(locale, { ru: "Цель", en: "Goal", ar: "الهدف", tr: "Hedef" })}: {number(locale, target)}</span><span>{l(locale, { ru: "Фактически", en: "Actual", ar: "الفعلي", tr: "Gerçek" })}: <strong>{number(locale, actual)}</strong></span></div><ProgressBar value={actual} max={target}/><div className="prayer-row-actions"><button onClick={() => addPages(prayer.code, 1)}><Icon name="plus" size={17}/>{l(locale, { ru: "Добавить вручную", en: "Add manually", ar: "إضافة يدويًا", tr: "Elle ekle" })}</button><button><Icon name="book" size={17}/>{l(locale, { ru: "Читать", en: "Read", ar: "اقرأ", tr: "Oku" })}</button></div></article>;
      })}</div>
      <div className="calm-note"><Icon name="spark"/><span>{l(locale, { ru: "Следующий спокойный шаг — две страницы после ближайшей молитвы.", en: "Your next gentle step is two pages after the next prayer.", ar: "خطوتك الهادئة التالية: صفحتان بعد الصلاة القادمة.", tr: "Bir sonraki sakin adım: gelecek namazdan sonra iki sayfa." })}</span></div>
    </Screen>
  );
}

export function PrayerScreen() {
  const { state, setState, navigate } = usePrototype();
  const locale = state.locale;
  return (
    <Screen className="prayer-screen">
      <TopBar back title={l(locale, { ru: "Намаз", en: "Prayer", ar: "الصلاة", tr: "Namaz" })} subtitle={l(locale, { ru: "Стамбул · Europe/Istanbul", en: "Istanbul · Europe/Istanbul", ar: "إسطنبول · Europe/Istanbul", tr: "İstanbul · Europe/Istanbul" })} action={<IconButton label="Prayer settings" onClick={() => navigate("settings")}><Icon name="settings"/></IconButton>}/>
      <section className="prayer-hero"><div className="sky-orbit"/><span className="eyebrow light">{l(locale, { ru: "Следующая молитва", en: "Next prayer", ar: "الصلاة التالية", tr: "Sonraki namaz" })}</span><h1>{l(locale, { ru: "Магриб", en: "Maghrib", ar: "المغرب", tr: "Akşam" })}</h1><div className="hero-prayer-time">19:42</div><p>{l(locale, { ru: "Осталось 1 ч 18 мин", en: "1h 18m remaining", ar: "متبقي ساعة و١٨ دقيقة", tr: "1 sa 18 dk kaldı" })}</p><div className="location-chip"><Icon name="map" size={17}/>İstanbul · <span>UTC+3</span></div></section>
      <section className="prayer-schedule-card"><div className="section-heading"><div><span className="eyebrow">{l(locale, { ru: "30 августа", en: "30 August", ar: "٣٠ أغسطس", tr: "30 Ağustos" })}</span><h2>{l(locale, { ru: "Сегодняшнее расписание", en: "Today’s schedule", ar: "مواقيت اليوم", tr: "Bugünün vakitleri" })}</h2></div><Icon name="calendar"/></div>{prayerTimes.map((prayer) => <div className={`prayer-time-row ${prayer.code === "maghrib" ? "is-next" : ""}`} key={prayer.code}><span className="prayer-row-icon"><Icon name={prayer.code === "fajr" || prayer.code === "isha" ? "moon" : "sun"}/></span><span><strong>{prayer[locale]}</strong><small>{prayer.ar}</small></span><time>{prayer.time}</time><Toggle checked={state.prayerNotifications[prayer.code]} onChange={() => setState((current) => ({ ...current, prayerNotifications: { ...current.prayerNotifications, [prayer.code]: !current.prayerNotifications[prayer.code] } }))} label={`${prayer[locale]} notification`}/></div>)}</section>
      <section className="after-prayer-toggle"><span className="list-icon sand"><Icon name="book"/></span><span><strong>{l(locale, { ru: "Предложить чтение после намаза", en: "Suggest reading after prayer", ar: "اقتراح القراءة بعد الصلاة", tr: "Namaz sonrası okuma öner" })}</strong><small>{l(locale, { ru: "Отдельно от уведомления о молитве", en: "Independent from prayer time alerts", ar: "مستقل عن تنبيه وقت الصلاة", tr: "Namaz vakti bildiriminden bağımsız" })}</small></span><Toggle checked={state.afterPrayerPrompt} onChange={() => setState((current) => ({ ...current, afterPrayerPrompt: !current.afterPrayerPrompt }))} label="After prayer reading prompt"/></section>
      <section className="prayer-method"><div><small>{l(locale, { ru: "Метод расчёта", en: "Calculation method", ar: "طريقة الحساب", tr: "Hesaplama yöntemi" })}</small><strong>Muslim World League</strong></div><div><small>{l(locale, { ru: "Мазхаб Асра", en: "Asr madhhab", ar: "مذهب العصر", tr: "İkindi mezhebi" })}</small><strong>{l(locale, { ru: "Стандартный", en: "Standard", ar: "قياسي", tr: "Standart" })}</strong></div><button className="button secondary wide" onClick={() => navigate("settings")}>{l(locale, { ru: "Расширенные настройки", en: "Advanced settings", ar: "الإعدادات المتقدمة", tr: "Gelişmiş ayarlar" })}<Icon name="chevron"/></button></section>
      <p className="privacy-note"><Icon name="shield" size={17}/>{l(locale, { ru: "Координаты используются только для расчёта и не сохраняются в профиле.", en: "Coordinates are used only for calculation and are not stored in your profile.", ar: "تُستخدم الإحداثيات للحساب فقط ولا تُحفظ في ملفك.", tr: "Koordinatlar yalnızca hesaplama için kullanılır ve profilinizde saklanmaz." })}</p>
    </Screen>
  );
}

export function MemorizationScreen() {
  const { state, setState, notify } = usePrototype();
  const locale = state.locale;
  const memorization = state.memorization;
  const reciter = reciters.find((item) => item.id === state.selectedReciter) || reciters[0];
  const increment = () => setState((current) => ({ ...current, player: { ...current.player, active: true, playing: true, ayah: current.memorization.startAyah, reciterId: current.selectedReciter }, memorization: { ...current.memorization, completedRepetitions: Math.min(current.memorization.targetRepetitions, current.memorization.completedRepetitions + 1) } }));
  return (
    <Screen className="memorization-screen">
      <TopBar back title={l(locale, { ru: "Заучивание", en: "Memorization", ar: "الحفظ", tr: "Ezber" })} subtitle={l(locale, { ru: "Маленькими повторениями", en: "One repetition at a time", ar: "تكرارًا بعد تكرار", tr: "Her seferinde bir tekrar" })} action={<IconButton label="Reset today" onClick={() => setState((current) => ({ ...current, modal: "memorization-reset" }))}><Icon name="refresh"/></IconButton>}/>
      <section className="memorization-plan"><div><span className="eyebrow light">{l(locale, { ru: "Текущий план", en: "Current plan", ar: "الخطة الحالية", tr: "Mevcut plan" })}</span><h1>{locale === "ar" ? "الفاتحة" : "Аль-Фатиха"}</h1><p>{l(locale, { ru: `Аяты ${memorization.startAyah}–${memorization.endAyah}`, en: `Ayahs ${memorization.startAyah}–${memorization.endAyah}`, ar: `الآيات ${number(locale, memorization.startAyah)}–${number(locale, memorization.endAyah)}`, tr: `Ayetler ${memorization.startAyah}–${memorization.endAyah}` })}</p></div><button className="button inverse small"><Icon name="edit"/>{l(locale, { ru: "Изменить", en: "Edit", ar: "تعديل", tr: "Düzenle" })}</button></section>
      <section className="memorization-settings"><label><span>{l(locale, { ru: "Начальный аят", en: "Start ayah", ar: "آية البداية", tr: "Başlangıç ayeti" })}</span><input type="number" min="1" max="7" value={memorization.startAyah} onChange={(event) => setState((current) => ({ ...current, memorization: { ...current.memorization, startAyah: Number(event.target.value) } }))}/></label><label><span>{l(locale, { ru: "Конечный аят", en: "End ayah", ar: "آية النهاية", tr: "Bitiş ayeti" })}</span><input type="number" min="1" max="7" value={memorization.endAyah} onChange={(event) => setState((current) => ({ ...current, memorization: { ...current.memorization, endAyah: Number(event.target.value) } }))}/></label><label><span>{l(locale, { ru: "Повторов", en: "Repetitions", ar: "التكرارات", tr: "Tekrar" })}</span><select value={memorization.targetRepetitions} onChange={(event) => setState((current) => ({ ...current, memorization: { ...current.memorization, targetRepetitions: Number(event.target.value) } }))}><option>3</option><option>5</option><option>10</option></select></label><label><span>{l(locale, { ru: "Пауза", en: "Pause", ar: "الفاصل", tr: "Ara" })}</span><select value={memorization.pauseSeconds} onChange={(event) => setState((current) => ({ ...current, memorization: { ...current.memorization, pauseSeconds: Number(event.target.value) } }))}><option value="0">0 s</option><option value="2">2 s</option><option value="5">5 s</option></select></label></section>
      <section className="tajweed-card"><div className="tajweed-head"><span><strong>{l(locale, { ru: "Таджвид", en: "Tajweed", ar: "التجويد", tr: "Tecvid" })}</strong><small>QCF V4 Tajweed · {l(locale, { ru: "из API", en: "from API", ar: "من الواجهة البرمجية", tr: "API'den" })}</small></span><span className="status-dot"><Icon name="check" size={15}/></span></div>{alFatihaAyahs.slice(memorization.startAyah - 1, memorization.endAyah).map((ayah, index) => <div className="memorization-ayah" key={ayah}><span>{number(locale, memorization.startAyah + index)}</span><p lang="ar" dir="rtl">{ayah}</p><Icon name="volume"/></div>)}</section>
      <section className="memorization-player"><div className="memorization-reciter"><span className="reciter-avatar small">{reciter.initials}</span><span><small>{l(locale, { ru: "Чтец", en: "Reciter", ar: "القارئ", tr: "Kâri" })}</small><strong>{reciter[locale]}</strong></span><Icon name="chevron"/></div><div className="counter-ring"><span><strong>{number(locale, memorization.completedRepetitions)}</strong><small>/ {number(locale, memorization.targetRepetitions)}</small></span></div><button className="button primary wide" onClick={increment}><Icon name="play" filled/>{memorization.completedRepetitions ? l(locale, { ru: "Следующий повтор", en: "Next repetition", ar: "التكرار التالي", tr: "Sonraki tekrar" }) : l(locale, { ru: "Начать повтор", en: "Start repetition", ar: "بدء التكرار", tr: "Tekrarı başlat" })}</button><ProgressBar value={memorization.completedRepetitions} max={memorization.targetRepetitions}/></section>
      {memorization.completedRepetitions > 0 ? <section className="assessment"><span className="eyebrow">{l(locale, { ru: "Как получилось?", en: "How did it feel?", ar: "كيف كان أداؤك؟", tr: "Nasıl hissettirdi?" })}</span><div><button className={memorization.assessment === "again" ? "is-active" : ""} onClick={() => setState((current) => ({ ...current, memorization: { ...current.memorization, assessment: "again" } }))}>{l(locale, { ru: "Ещё раз", en: "Again", ar: "مرة أخرى", tr: "Tekrar" })}</button><button className={memorization.assessment === "hard" ? "is-active" : ""} onClick={() => setState((current) => ({ ...current, memorization: { ...current.memorization, assessment: "hard" } }))}>{l(locale, { ru: "Сложно", en: "Hard", ar: "صعب", tr: "Zor" })}</button><button className={memorization.assessment === "good" ? "is-active" : ""} onClick={() => setState((current) => ({ ...current, memorization: { ...current.memorization, assessment: "good" } }))}>{l(locale, { ru: "Хорошо", en: "Good", ar: "جيد", tr: "İyi" })}</button></div></section> : null}
      <section className="coming-feature"><Icon name="spark"/><span><strong>{l(locale, { ru: "Интервальное повторение", en: "Spaced repetition", ar: "المراجعة المتباعدة", tr: "Aralıklı tekrar" })}</strong><small>{l(locale, { ru: "Следующий этап", en: "Next stage", ar: "المرحلة التالية", tr: "Sonraki aşama" })}</small></span><span className="soon-badge">{l(locale, { ru: "Скоро", en: "Soon", ar: "قريبًا", tr: "Yakında" })}</span></section>
      {state.modal === "memorization-reset" ? <div className="dialog-backdrop"><section className="confirm-dialog" role="alertdialog"><span className="dialog-icon"><Icon name="refresh"/></span><h2>{l(locale, { ru: "Сбросить счётчик сегодня?", en: "Reset today’s counter?", ar: "إعادة ضبط عداد اليوم؟", tr: "Bugünkü sayacı sıfırla?" })}</h2><p>{l(locale, { ru: "План и история прошлых дней сохранятся.", en: "Your plan and previous history will stay intact.", ar: "ستبقى خطتك وسجل الأيام السابقة محفوظين.", tr: "Planınız ve geçmiş günlerin kaydı korunur." })}</p><div><button className="button secondary" onClick={() => setState((current) => ({ ...current, modal: "" }))}>{l(locale, { ru: "Отмена", en: "Cancel", ar: "إلغاء", tr: "İptal" })}</button><button className="button danger" onClick={() => { setState((current) => ({ ...current, modal: "", memorization: { ...current.memorization, completedRepetitions: 0, assessment: "" } })); notify(l(locale, { ru: "Сегодняшний счётчик сброшен", en: "Today’s counter reset", ar: "تمت إعادة ضبط عداد اليوم", tr: "Bugünkü sayaç sıfırlandı" })); }}>{l(locale, { ru: "Сбросить", en: "Reset", ar: "إعادة ضبط", tr: "Sıfırla" })}</button></div></section></div> : null}
    </Screen>
  );
}
