# ruff: noqa: RUF001
# Generated by Django 6.1 on 2026-08-29 22:53

import django.db.models.deletion
import django.utils.timezone
import quran_backend.modules.share_referrals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        default=quran_backend.modules.share_referrals.models.generate_referral_code,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Промокод",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="Включена")),
                (
                    "disabled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Отключена"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Отозвана"),
                ),
                (
                    "state_reason",
                    models.CharField(blank=True, max_length=500, verbose_name="Причина"),
                ),
                (
                    "disabled_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disabled_referral_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отключил",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referral_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revoked_referral_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отозвал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Реферальная ссылка / промокод",
                "verbose_name_plural": "Реферальные ссылки / промокоды",
                "db_table": "share_referral_link",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ReferralAttribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual_admin", "Manual admin review"),
                            ("signup_hook", "Verified signup hook"),
                        ],
                        max_length=20,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(
                        default=uuid.uuid7, unique=True, verbose_name="Ключ идемпотентности"
                    ),
                ),
                (
                    "attributed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Атрибуция"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_referral_attributions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referral_attributions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Приглашённый аккаунт",
                    ),
                ),
                (
                    "referral_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attributions",
                        to="share_referrals.referrallink",
                        verbose_name="Реферальный код",
                    ),
                ),
            ],
            options={
                "verbose_name": "Атрибуция приглашения",
                "verbose_name_plural": "Атрибуции приглашений",
                "db_table": "share_referral_attribution",
                "ordering": ("-attributed_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ReferralQualification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("qualified", "Qualified"),
                            ("rejected", "Rejected"),
                            ("reversed", "Reversed"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Решение принято"),
                ),
                (
                    "decision_reason",
                    models.CharField(blank=True, max_length=500, verbose_name="Основание"),
                ),
                (
                    "attribution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qualification",
                        to="share_referrals.referralattribution",
                        verbose_name="Атрибуция",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decided_referral_qualifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Решение принял",
                    ),
                ),
            ],
            options={
                "verbose_name": "Квалификация приглашения",
                "verbose_name_plural": "Квалификации приглашений",
                "db_table": "share_referral_qualification",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ReferralReward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("points", models.PositiveIntegerField(verbose_name="Баллы")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending approval"),
                            ("approved", "Approved"),
                            ("reversed", "Reversed"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        editable=False,
                        max_length=160,
                        unique=True,
                        verbose_name="Ключ идемпотентности",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Одобрено"),
                ),
                (
                    "reversed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Отменено"),
                ),
                (
                    "reversal_reason",
                    models.CharField(blank=True, max_length=500, verbose_name="Причина отмены"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_referral_rewards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Одобрил",
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referral_rewards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
                (
                    "qualification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reward",
                        to="share_referrals.referralqualification",
                        verbose_name="Квалификация",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_referral_rewards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отменил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Начисление за приглашение",
                "verbose_name_plural": "Начисления за приглашения",
                "db_table": "share_referral_reward",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ReferralRewardAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created pending"),
                            ("approved", "Approved"),
                            ("reversed", "Reversed"),
                        ],
                        max_length=16,
                        verbose_name="Операция",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(blank=True, max_length=16, verbose_name="Было"),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending approval"),
                            ("approved", "Approved"),
                            ("reversed", "Reversed"),
                        ],
                        max_length=16,
                        verbose_name="Стало",
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=500, verbose_name="Причина")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referral_reward_audits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Оператор",
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="share_referrals.referralreward",
                        verbose_name="Начисление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аудит начисления",
                "verbose_name_plural": "Аудит начислений",
                "db_table": "share_referral_reward_audit",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ShareCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.SlugField(
                        help_text="Не меняйте после выпуска клиента, например app-invite.",
                        max_length=64,
                        unique=True,
                        verbose_name="Стабильный ключ",
                    ),
                ),
                (
                    "internal_name",
                    models.CharField(max_length=120, verbose_name="Название для команды"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Кампания доступна только внутри указанного временного окна.",
                        verbose_name="Включена",
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True, verbose_name="Начало")),
                ("ends_at", models.DateTimeField(blank=True, null=True, verbose_name="Окончание")),
                (
                    "canonical_download_url",
                    models.URLField(
                        help_text="Доверенный HTTPS-адрес. Публичный referral redirect ведёт только сюда.",
                        max_length=500,
                        verbose_name="Основная страница загрузки",
                    ),
                ),
                (
                    "ios_url",
                    models.URLField(blank=True, max_length=500, verbose_name="App Store URL"),
                ),
                (
                    "android_url",
                    models.URLField(blank=True, max_length=500, verbose_name="Google Play URL"),
                ),
                (
                    "short_link_base_url",
                    models.URLField(
                        blank=True,
                        help_text="Например https://iqro.app/r. Если пусто, API использует свой /r/ путь.",
                        max_length=500,
                        verbose_name="База коротких ссылок",
                    ),
                ),
                (
                    "referral_enabled",
                    models.BooleanField(default=True, verbose_name="Рефералы включены"),
                ),
                (
                    "reward_points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Начисление создаётся сервером после квалификации; 0 отключает бонус.",
                        verbose_name="Баллов за подтверждённое приглашение",
                    ),
                ),
                (
                    "priority",
                    models.SmallIntegerField(
                        default=100,
                        help_text="При запросе без ключа выбирается активная кампания с большим приоритетом.",
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "config_version",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="Версия конфигурации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Кампания «Поделиться»",
                "verbose_name_plural": "Кампании «Поделиться»",
                "db_table": "share_campaign",
                "ordering": ("-priority", "key"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "priority", "starts_at", "ends_at"],
                        name="share_campaign_active_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ends_at__isnull", True),
                            ("starts_at__isnull", True),
                            ("ends_at__gt", models.F("starts_at")),
                            _connector="OR",
                        ),
                        name="share_campaign_valid_window",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="referralreward",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rewards",
                to="share_referrals.sharecampaign",
                verbose_name="Кампания",
            ),
        ),
        migrations.AddField(
            model_name="referrallink",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referral_links",
                to="share_referrals.sharecampaign",
                verbose_name="Кампания",
            ),
        ),
        migrations.CreateModel(
            name="ReferralClick",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("system", "System share sheet"),
                            ("copy", "Copy"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                        verbose_name="Канал",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Получено"),
                ),
                (
                    "referral_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clicks",
                        to="share_referrals.referrallink",
                        verbose_name="Реферальный код",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referral_clicks",
                        to="share_referrals.sharecampaign",
                        verbose_name="Кампания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Переход по короткой ссылке",
                "verbose_name_plural": "Переходы по коротким ссылкам",
                "db_table": "share_referral_click",
                "ordering": ("-received_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="referralattribution",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attributions",
                to="share_referrals.sharecampaign",
                verbose_name="Кампания",
            ),
        ),
        migrations.CreateModel(
            name="ShareCampaignCopy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locale", models.CharField(max_length=8, verbose_name="Язык")),
                ("title", models.CharField(max_length=160, verbose_name="Заголовок")),
                ("message", models.TextField(max_length=1200, verbose_name="Текст для отправки")),
                (
                    "cta_label",
                    models.CharField(blank=True, max_length=80, verbose_name="Текст кнопки"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localized_copies",
                        to="share_referrals.sharecampaign",
                        verbose_name="Кампания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод кампании",
                "verbose_name_plural": "Переводы кампаний",
                "db_table": "share_campaign_copy",
                "ordering": ("campaign", "locale"),
            },
        ),
        migrations.CreateModel(
            name="ShareEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_event_id",
                    models.UUIDField(unique=True, verbose_name="ID события на клиенте"),
                ),
                (
                    "account_mode",
                    models.CharField(
                        choices=[("guest", "Guest"), ("verified", "Verified account")],
                        max_length=16,
                        verbose_name="Тип аккаунта",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("opened", "Opened"),
                            ("share_sheet_opened", "Share sheet opened"),
                            ("link_copied", "Link copied"),
                            ("referral_code_copied", "Referral code copied"),
                            ("share_completed", "Share completed"),
                            ("referral_code_entered", "Referral code entered"),
                        ],
                        max_length=32,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("succeeded", "Succeeded"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                        verbose_name="Результат",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("system", "System share sheet"),
                            ("copy", "Copy"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                        verbose_name="Канал",
                    ),
                ),
                ("occurred_at", models.DateTimeField(verbose_name="Произошло на клиенте")),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Получено"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Безопасные метаданные"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="share_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Аккаунт",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="share_events",
                        to="share_referrals.sharecampaign",
                        verbose_name="Кампания",
                    ),
                ),
                (
                    "referral_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="share_events",
                        to="share_referrals.referrallink",
                        verbose_name="Реферальный код",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие «Поделиться»",
                "verbose_name_plural": "События «Поделиться»",
                "db_table": "share_event",
                "ordering": ("-received_at", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="referralreward",
            index=models.Index(
                fields=["beneficiary", "status", "created_at"], name="share_reward_balance_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="referralreward",
            constraint=models.CheckConstraint(
                condition=models.Q(("points__gt", 0)), name="share_reward_points_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="referralreward",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "approved"), _negated=True),
                    models.Q(("approved_at__isnull", False), ("approved_by__isnull", False)),
                    _connector="OR",
                ),
                name="share_reward_approved_audit",
            ),
        ),
        migrations.AddConstraint(
            model_name="referralreward",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "reversed"), _negated=True),
                    models.Q(("reversed_at__isnull", False), ("reversed_by__isnull", False)),
                    _connector="OR",
                ),
                name="share_reward_reversed_audit",
            ),
        ),
        migrations.AddIndex(
            model_name="referrallink",
            index=models.Index(
                fields=["campaign", "is_enabled", "revoked_at"], name="share_referral_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="referrallink",
            constraint=models.UniqueConstraint(
                fields=("campaign", "owner"), name="share_referral_campaign_owner_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="referrallink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("revoked_at__isnull", True), ("revoked_by__isnull", True)),
                    models.Q(("revoked_at__isnull", False), ("revoked_by__isnull", False)),
                    _connector="OR",
                ),
                name="share_referral_revocation_shape",
            ),
        ),
        migrations.AddIndex(
            model_name="referralclick",
            index=models.Index(fields=["campaign", "received_at"], name="share_click_campaign_idx"),
        ),
        migrations.AddIndex(
            model_name="referralattribution",
            index=models.Index(
                fields=["referral_link", "attributed_at"], name="share_attribution_link_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="referralattribution",
            constraint=models.UniqueConstraint(
                fields=("campaign", "invitee"), name="share_attribution_campaign_invitee_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sharecampaigncopy",
            constraint=models.UniqueConstraint(
                fields=("campaign", "locale"), name="share_campaign_copy_locale_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sharecampaigncopy",
            constraint=models.CheckConstraint(
                condition=models.Q(("locale__in", ("ar", "en", "ru", "tr"))),
                name="share_campaign_copy_locale_supported",
            ),
        ),
        migrations.AddIndex(
            model_name="shareevent",
            index=models.Index(
                fields=["campaign", "action", "received_at"], name="share_event_analytics_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shareevent",
            index=models.Index(fields=["actor", "received_at"], name="share_event_actor_idx"),
        ),
    ]
