# Generated by Django 6.1 on 2026-08-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("share_referrals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referralattribution",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual_admin", "Подтверждено сотрудником"),
                    ("signup_hook", "Подтверждено сервером при регистрации"),
                ],
                max_length=20,
                verbose_name="Источник",
            ),
        ),
        migrations.AlterField(
            model_name="referralclick",
            name="channel",
            field=models.CharField(
                choices=[
                    ("system", "Системное меню устройства"),
                    ("copy", "Копирование"),
                    ("whatsapp", "WhatsApp"),
                    ("telegram", "Telegram"),
                    ("email", "Электронная почта"),
                    ("sms", "Сообщение SMS"),
                    ("other", "Другой канал"),
                ],
                default="other",
                max_length=16,
                verbose_name="Канал",
            ),
        ),
        migrations.AlterField(
            model_name="referralqualification",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает проверки"),
                    ("qualified", "Подтверждено"),
                    ("rejected", "Отклонено"),
                    ("reversed", "Отменено после подтверждения"),
                ],
                default="pending",
                max_length=16,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="referralreward",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает одобрения"),
                    ("approved", "Начислено"),
                    ("reversed", "Отменено"),
                ],
                default="pending",
                max_length=16,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="referralrewardaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Создан ожидающий бонус"),
                    ("approved", "Бонус начислен"),
                    ("reversed", "Бонус отменён"),
                ],
                max_length=16,
                verbose_name="Операция",
            ),
        ),
        migrations.AlterField(
            model_name="referralrewardaudit",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает одобрения"),
                    ("approved", "Начислено"),
                    ("reversed", "Отменено"),
                ],
                max_length=16,
                verbose_name="Стало",
            ),
        ),
        migrations.AlterField(
            model_name="shareevent",
            name="account_mode",
            field=models.CharField(
                choices=[("guest", "Гостевой профиль"), ("verified", "Подтверждённый аккаунт")],
                max_length=16,
                verbose_name="Тип аккаунта",
            ),
        ),
        migrations.AlterField(
            model_name="shareevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("opened", "Открыл раздел приглашений"),
                    ("share_sheet_opened", "Открыл системное меню «Поделиться»"),
                    ("link_copied", "Скопировал ссылку"),
                    ("referral_code_copied", "Скопировал промокод"),
                    ("share_completed", "Отправил приглашение"),
                    ("referral_code_entered", "Ввёл промокод"),
                ],
                max_length=32,
                verbose_name="Действие",
            ),
        ),
        migrations.AlterField(
            model_name="shareevent",
            name="channel",
            field=models.CharField(
                choices=[
                    ("system", "Системное меню устройства"),
                    ("copy", "Копирование"),
                    ("whatsapp", "WhatsApp"),
                    ("telegram", "Telegram"),
                    ("email", "Электронная почта"),
                    ("sms", "Сообщение SMS"),
                    ("other", "Другой канал"),
                ],
                max_length=16,
                verbose_name="Канал",
            ),
        ),
        migrations.AlterField(
            model_name="shareevent",
            name="result",
            field=models.CharField(
                choices=[
                    ("started", "Начато"),
                    ("succeeded", "Успешно"),
                    ("cancelled", "Отменено пользователем"),
                    ("failed", "Ошибка"),
                ],
                max_length=16,
                verbose_name="Результат",
            ),
        ),
    ]
