# Generated by Django 6.1 on 2026-08-28 18:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DuaCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "dua_collection",
                "ordering": ("slug",),
            },
        ),
        migrations.CreateModel(
            name="DuaCollectionVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=64)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("checksum_sha256", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("category_count", models.PositiveIntegerField(default=0)),
                ("entry_count", models.PositiveIntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="dua.duacollection",
                    ),
                ),
            ],
            options={
                "db_table": "dua_collection_version",
                "ordering": ("collection", "-created_at"),
            },
        ),
        migrations.AddField(
            model_name="duacollection",
            name="active_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_collections",
                to="dua.duacollectionversion",
            ),
        ),
        migrations.CreateModel(
            name="DuaCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_number", models.PositiveSmallIntegerField()),
                ("slug", models.SlugField(max_length=120)),
                ("sort_order", models.PositiveSmallIntegerField()),
                (
                    "collection_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categories",
                        to="dua.duacollectionversion",
                    ),
                ),
            ],
            options={
                "db_table": "dua_category",
                "ordering": ("sort_order", "source_number"),
            },
        ),
        migrations.CreateModel(
            name="DuaEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_number", models.PositiveSmallIntegerField()),
                ("slug", models.SlugField(max_length=120)),
                ("arabic_text", models.TextField()),
                ("repetitions", models.PositiveSmallIntegerField(default=1)),
                ("sort_order", models.PositiveSmallIntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="dua.duacategory",
                    ),
                ),
                (
                    "collection_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="dua.duacollectionversion",
                    ),
                ),
            ],
            options={
                "db_table": "dua_entry",
                "ordering": ("sort_order", "source_number"),
            },
        ),
        migrations.CreateModel(
            name="DuaEntryTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("language_code", models.CharField(max_length=8)),
                ("meaning_text", models.TextField()),
                ("transliteration", models.TextField(blank=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="dua.duaentry",
                    ),
                ),
            ],
            options={
                "db_table": "dua_entry_translation",
                "ordering": ("language_code",),
            },
        ),
        migrations.CreateModel(
            name="DuaEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("hadith", "Hadith"),
                            ("quran", "Quran"),
                            ("source_note", "Source note"),
                        ],
                        max_length=16,
                    ),
                ),
                ("provider", models.CharField(max_length=64)),
                ("source_name", models.CharField(max_length=255)),
                ("source_reference", models.CharField(max_length=500)),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("grade", models.CharField(blank=True, max_length=255)),
                ("external_id", models.CharField(blank=True, max_length=64)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("source_only", "Copied from source edition"),
                            ("editorially_verified", "Editorially verified"),
                        ],
                        default="source_only",
                        max_length=32,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=1)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="dua.duaentry",
                    ),
                ),
            ],
            options={
                "db_table": "dua_evidence",
                "ordering": ("sort_order", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="DuaSourceEdition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("language_code", models.CharField(max_length=8)),
                ("provider", models.CharField(max_length=64)),
                ("source_item_id", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("translator", models.CharField(blank=True, max_length=255)),
                ("reviewer", models.CharField(blank=True, max_length=255)),
                ("source_url", models.URLField(max_length=500)),
                ("rights_url", models.URLField(max_length=500)),
                ("source_version", models.CharField(max_length=64)),
                (
                    "collection_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_editions",
                        to="dua.duacollectionversion",
                    ),
                ),
            ],
            options={
                "db_table": "dua_source_edition",
                "ordering": ("language_code",),
            },
        ),
        migrations.CreateModel(
            name="DuaCategoryTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("language_code", models.CharField(max_length=8)),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="dua.duacategory",
                    ),
                ),
            ],
            options={
                "db_table": "dua_category_translation",
                "ordering": ("language_code",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "language_code"), name="dua_category_translation_unique"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="duacollectionversion",
            index=models.Index(fields=["status", "collection"], name="dua_version_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="duacollectionversion",
            constraint=models.UniqueConstraint(
                fields=("collection", "version"), name="dua_collection_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="duacollectionversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_version__gt", 0)), name="dua_version_schema_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="duacollectionversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("published_at__isnull", False), ("status", "published")),
                    models.Q(("status", "published"), _negated=True),
                    _connector="OR",
                ),
                name="dua_published_version_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="duacategory",
            constraint=models.UniqueConstraint(
                fields=("collection_version", "source_number"),
                name="dua_category_source_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="duacategory",
            constraint=models.UniqueConstraint(
                fields=("collection_version", "slug"), name="dua_category_slug_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="duaentry",
            index=models.Index(
                fields=["collection_version", "category", "sort_order"],
                name="dua_entry_catalog_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="duaentry",
            constraint=models.UniqueConstraint(
                fields=("collection_version", "source_number"),
                name="dua_entry_source_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="duaentry",
            constraint=models.UniqueConstraint(
                fields=("collection_version", "slug"), name="dua_entry_slug_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="duaentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("repetitions__gt", 0)), name="dua_entry_repetitions_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="duaentrytranslation",
            constraint=models.UniqueConstraint(
                fields=("entry", "language_code"), name="dua_entry_translation_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="duaevidence",
            constraint=models.UniqueConstraint(
                fields=("entry", "sort_order"), name="dua_evidence_entry_order_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="duasourceedition",
            constraint=models.UniqueConstraint(
                fields=("collection_version", "language_code"),
                name="dua_source_edition_language_unique",
            ),
        ),
    ]
