# Generated by Django 6.1 on 2026-08-28 12:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TafsirEdition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("environment", models.CharField(max_length=16)),
                ("provider", models.CharField(default="quran_foundation", max_length=32)),
                ("source_id", models.PositiveIntegerField()),
                ("slug", models.SlugField(max_length=128)),
                ("language_code", models.CharField(db_index=True, max_length=8)),
                ("language_name", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("author_name", models.CharField(max_length=255)),
                ("source_name", models.CharField(max_length=255)),
                ("source_url", models.URLField()),
                ("license_name", models.CharField(max_length=255)),
                ("license_url", models.URLField()),
                ("attribution", models.CharField(max_length=500)),
                ("is_available", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "tafsir_edition",
                "ordering": ["language_code", "name", "source_id"],
            },
        ),
        migrations.CreateModel(
            name="QuranFoundationTafsirSyncState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("environment", models.CharField(max_length=16)),
                ("resources_filter", models.CharField(max_length=255)),
                ("sync_token", models.TextField(blank=True)),
                ("last_sync_sequence", models.PositiveBigIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "db_table": "tafsir_qf_sync_state",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("environment", "resources_filter"),
                        name="tafsir_qf_sync_state_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TafsirEditionVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sync_sequence", models.PositiveBigIntegerField()),
                ("schema_version", models.CharField(max_length=32)),
                ("checksum_sha256", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("record_count", models.PositiveSmallIntegerField()),
                ("covered_ayah_count", models.PositiveSmallIntegerField()),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="tafsirs.tafsiredition",
                    ),
                ),
            ],
            options={
                "db_table": "tafsir_edition_version",
                "ordering": ["-sync_sequence"],
            },
        ),
        migrations.AddField(
            model_name="tafsiredition",
            name="active_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_editions",
                to="tafsirs.tafsireditionversion",
            ),
        ),
        migrations.CreateModel(
            name="AyahTafsir",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_id", models.PositiveBigIntegerField()),
                ("provider_group_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("verse_key", models.CharField(max_length=16)),
                ("surah_number", models.PositiveSmallIntegerField()),
                ("ayah_number", models.PositiveSmallIntegerField()),
                ("start_verse_id", models.PositiveSmallIntegerField()),
                ("end_verse_id", models.PositiveSmallIntegerField()),
                ("start_verse_key", models.CharField(max_length=16)),
                ("end_verse_key", models.CharField(max_length=16)),
                ("start_surah_number", models.PositiveSmallIntegerField()),
                ("start_ayah_number", models.PositiveSmallIntegerField()),
                ("end_surah_number", models.PositiveSmallIntegerField()),
                ("end_ayah_number", models.PositiveSmallIntegerField()),
                ("group_verses_count", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                ("source_text", models.TextField()),
                (
                    "edition_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ayah_tafsirs",
                        to="tafsirs.tafsireditionversion",
                    ),
                ),
            ],
            options={
                "db_table": "tafsir_ayah",
                "ordering": ["surah_number", "ayah_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="tafsireditionversion",
            constraint=models.UniqueConstraint(
                fields=("edition", "sync_sequence"), name="tafsir_version_sequence_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="tafsireditionversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("record_count__gt", 0)),
                name="tafsir_version_positive_record_count",
            ),
        ),
        migrations.AddConstraint(
            model_name="tafsireditionversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("covered_ayah_count__gt", 0)),
                name="tafsir_version_positive_coverage",
            ),
        ),
        migrations.AddConstraint(
            model_name="tafsireditionversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("published_at__isnull", False), ("status", "published")),
                    models.Q(("status", "published"), _negated=True),
                    _connector="OR",
                ),
                name="tafsir_published_version_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="tafsiredition",
            constraint=models.UniqueConstraint(
                fields=("environment", "provider", "source_id"),
                name="tafsir_edition_provider_source_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="ayahtafsir",
            index=models.Index(
                fields=["edition_version", "surah_number", "ayah_number"],
                name="tafsir_ayah_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ayahtafsir",
            index=models.Index(
                fields=["edition_version", "start_verse_id", "end_verse_id"],
                name="tafsir_ayah_range_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="ayahtafsir",
            constraint=models.UniqueConstraint(
                fields=("edition_version", "source_id"), name="tafsir_ayah_version_source_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="ayahtafsir",
            constraint=models.UniqueConstraint(
                fields=("edition_version", "verse_key"), name="tafsir_ayah_version_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="ayahtafsir",
            constraint=models.CheckConstraint(
                condition=models.Q(("surah_number__gte", 1), ("surah_number__lte", 114)),
                name="tafsir_ayah_surah_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="ayahtafsir",
            constraint=models.CheckConstraint(
                condition=models.Q(("ayah_number__gte", 1)), name="tafsir_ayah_number_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="ayahtafsir",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_verse_id__gte", models.F("start_verse_id"))),
                name="tafsir_ayah_valid_range",
            ),
        ),
    ]
