# Generated by Django 6.1 on 2026-08-09 07:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_refresh_sessions"),
        ("quran", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("prayer", "Prayer"),
                            ("quran_reading", "Quran reading"),
                            ("quran_review", "Quran review"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "prayer_event",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fajr", "Fajr"),
                            ("dhuhr", "Dhuhr"),
                            ("asr", "Asr"),
                            ("maghrib", "Maghrib"),
                            ("isha", "Isha"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("local_time", models.TimeField(blank=True, null=True)),
                (
                    "prayer_offset_minutes",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-120),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "weekdays_mask",
                    models.PositiveSmallIntegerField(
                        default=127,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(127),
                        ],
                    ),
                ),
                (
                    "timezone_mode",
                    models.CharField(
                        choices=[
                            ("device_local", "Device local timezone"),
                            ("fixed", "Fixed timezone"),
                        ],
                        default="device_local",
                        max_length=16,
                    ),
                ),
                ("timezone_name", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[("local", "Local client notification")],
                        default="local",
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "signal",
                    models.CharField(
                        choices=[
                            ("silent", "Silent"),
                            ("vibration", "Vibration"),
                            ("sound", "Short system sound"),
                        ],
                        default="sound",
                        max_length=16,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("client_updated_at", models.DateTimeField()),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminder_rules",
                        to="accounts.device",
                    ),
                ),
                (
                    "end_ayah",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_reminders_as_end",
                        to="quran.ayah",
                    ),
                ),
                (
                    "start_ayah",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_reminders_as_start",
                        to="quran.ayah",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reminder_rule",
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "deleted_at", "updated_at"], name="reminder_user_sync_idx"
                    ),
                    models.Index(
                        fields=["user", "is_enabled", "reminder_type"],
                        name="reminder_user_active_idx",
                    ),
                    models.Index(
                        fields=["deleted_at", "id"],
                        name="reminder_retention_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("weekdays_mask__gte", 1), ("weekdays_mask__lte", 127)),
                        name="reminder_weekdays_mask_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("revision__gte", 1)), name="reminder_revision_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("delivery_mode", "local")),
                        name="reminder_delivery_local_only",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("signal__in", ["silent", "vibration", "sound"])),
                        name="reminder_signal_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("timezone_mode", "device_local"), ("timezone_name__isnull", True)
                            ),
                            models.Q(
                                ("timezone_mode", "fixed"),
                                ("timezone_name__isnull", False),
                                models.Q(("timezone_name", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="reminder_timezone_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("deleted_at__isnull", True),
                                models.Q(
                                    models.Q(
                                        ("end_ayah__isnull", True),
                                        ("local_time__isnull", True),
                                        (
                                            "prayer_event__in",
                                            ["fajr", "dhuhr", "asr", "maghrib", "isha"],
                                        ),
                                        ("prayer_offset_minutes__gte", -120),
                                        ("prayer_offset_minutes__lte", 120),
                                        ("reminder_type", "prayer"),
                                        ("start_ayah__isnull", True),
                                    ),
                                    models.Q(
                                        ("end_ayah__isnull", True),
                                        ("local_time__isnull", False),
                                        ("prayer_event__isnull", True),
                                        ("prayer_offset_minutes__isnull", True),
                                        ("reminder_type", "quran_reading"),
                                        ("start_ayah__isnull", True),
                                    ),
                                    models.Q(
                                        ("end_ayah__isnull", False),
                                        ("local_time__isnull", False),
                                        ("prayer_event__isnull", True),
                                        ("prayer_offset_minutes__isnull", True),
                                        ("reminder_type", "quran_review"),
                                        ("start_ayah__isnull", False),
                                    ),
                                    _connector="OR",
                                ),
                            ),
                            models.Q(
                                ("deleted_at__isnull", False),
                                ("end_ayah__isnull", True),
                                ("local_time__isnull", True),
                                ("prayer_event__isnull", True),
                                ("prayer_offset_minutes__isnull", True),
                                ("start_ayah__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="reminder_schedule_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("deleted_at__isnull", True), ("is_enabled", False), _connector="OR"
                        ),
                        name="reminder_tombstone_disabled",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("deleted_at__isnull", True),
                            models.Q(
                                ("device__isnull", True),
                                ("is_enabled", False),
                                ("signal", "silent"),
                                ("timezone_mode", "device_local"),
                                ("timezone_name__isnull", True),
                                ("weekdays_mask", 127),
                            ),
                            _connector="OR",
                        ),
                        name="reminder_tombstone_minimized",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RetiredReminderId",
            fields=[
                (
                    "reminder_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("last_revision", models.PositiveBigIntegerField()),
                ("retired_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retired_reminder_ids",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reminder_retired_id",
                "indexes": [
                    models.Index(
                        fields=["user", "retired_at"],
                        name="reminder_retired_user_time_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("last_revision__gte", 1)),
                        name="reminder_retired_revision_positive",
                    )
                ],
            },
        ),
    ]
