# Generated by Django 6.1 on 2026-08-26 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_support_turkish_locale"),
        ("reminders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebPushSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("endpoint", models.TextField(unique=True)),
                ("p256dh", models.CharField(max_length=128)),
                ("auth", models.CharField(max_length=64)),
                ("timezone_name", models.CharField(max_length=64)),
                ("locale", models.CharField(default="en", max_length=8)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveSmallIntegerField(default=0)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="web_push_subscription",
                        to="accounts.device",
                    ),
                ),
            ],
            options={
                "db_table": "reminder_web_push_subscription",
            },
        ),
        migrations.CreateModel(
            name="WebPushSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurrence_at", models.DateTimeField()),
                ("next_attempt_at", models.DateTimeField(db_index=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("claim_token", models.UUIDField(blank=True, null=True)),
                ("claimed_until", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="web_push_schedules",
                        to="reminders.reminderrule",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="reminders.webpushsubscription",
                    ),
                ),
            ],
            options={
                "db_table": "reminder_web_push_schedule",
            },
        ),
        migrations.AddIndex(
            model_name="webpushsubscription",
            index=models.Index(
                fields=["revoked_at", "updated_at"], name="reminder_push_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="webpushsubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("locale__in", ["ar", "en", "ru", "tr"])),
                name="reminder_push_supported_locale",
            ),
        ),
        migrations.AddConstraint(
            model_name="webpushsubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("consecutive_failures__lte", 100)),
                name="reminder_push_failures_bounded",
            ),
        ),
        migrations.AddIndex(
            model_name="webpushschedule",
            index=models.Index(
                fields=["next_attempt_at", "claimed_until"], name="reminder_push_due_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="webpushschedule",
            constraint=models.UniqueConstraint(
                fields=("subscription", "reminder"), name="reminder_push_schedule_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="webpushschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_count__lte", 100)),
                name="reminder_push_attempts_bounded",
            ),
        ),
    ]
