# Generated by Django 6.1 on 2026-08-27

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reminders", "0002_webpushsubscription_webpushschedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpushsubscription",
            name="prayer_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[MinValueValidator(-90), MaxValueValidator(90)],
            ),
        ),
        migrations.AddField(
            model_name="webpushsubscription",
            name="prayer_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=10,
                null=True,
                validators=[MinValueValidator(-180), MaxValueValidator(180)],
            ),
        ),
        migrations.AddConstraint(
            model_name="webpushsubscription",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(prayer_latitude__isnull=True, prayer_longitude__isnull=True)
                    | models.Q(prayer_latitude__isnull=False, prayer_longitude__isnull=False)
                ),
                name="reminder_push_prayer_location_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="webpushsubscription",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(prayer_latitude__isnull=True)
                    | models.Q(
                        prayer_latitude__gte=-90,
                        prayer_latitude__lte=90,
                        prayer_longitude__gte=-180,
                        prayer_longitude__lte=180,
                    )
                ),
                name="reminder_push_prayer_location_range",
            ),
        ),
    ]
