# Generated by Django 6.1 on 2026-08-09 05:48

import django.db.models.deletion
import quran_backend.modules.audio.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("quran", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioTimingVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.CharField(
                        max_length=64,
                        validators=[
                            quran_backend.modules.audio.validators.validate_version_identifier
                        ],
                    ),
                ),
                ("source_name", models.CharField(max_length=255)),
                ("source_version", models.CharField(max_length=128)),
                (
                    "source_checksum_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[quran_backend.modules.audio.validators.validate_sha256],
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "audio_timing_version",
                "ordering": ["recitation_edition", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecitationEdition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64)),
                (
                    "version",
                    models.CharField(
                        max_length=64,
                        validators=[
                            quran_backend.modules.audio.validators.validate_version_identifier
                        ],
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("murattal", "Murattal"),
                            ("mujawwad", "Mujawwad"),
                            ("muallim", "Muallim"),
                        ],
                        default="murattal",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("source_name", models.CharField(max_length=255)),
                ("source_url", models.URLField(blank=True)),
                ("source_version", models.CharField(max_length=128)),
                (
                    "source_checksum_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[quran_backend.modules.audio.validators.validate_sha256],
                    ),
                ),
                ("rights_holder", models.CharField(max_length=255)),
                ("license_name", models.CharField(max_length=255)),
                ("license_url", models.URLField(blank=True)),
                ("license_spdx_id", models.CharField(blank=True, max_length=64)),
                ("license_attribution", models.TextField(blank=True)),
                ("stream_allowed", models.BooleanField(blank=True, null=True)),
                ("offline_download_allowed", models.BooleanField(blank=True, null=True)),
                (
                    "quran_edition_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recitations",
                        to="quran.quraneditionversion",
                    ),
                ),
            ],
            options={
                "db_table": "audio_recitation_edition",
                "ordering": ["code", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AudioTrack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[("surah", "Surah"), ("juz", "Juz"), ("full", "Full Quran")],
                        max_length=8,
                    ),
                ),
                ("surah_number", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("juz_number", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("duration_ms", models.PositiveBigIntegerField()),
                (
                    "codec",
                    models.CharField(
                        choices=[
                            ("mp3", "MP3"),
                            ("aac", "AAC"),
                            ("opus", "Opus"),
                            ("flac", "FLAC"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("audio/mpeg", "audio/mpeg"),
                            ("audio/aac", "audio/aac"),
                            ("audio/ogg", "audio/ogg"),
                            ("audio/flac", "audio/flac"),
                        ],
                        default="audio/mpeg",
                        max_length=32,
                    ),
                ),
                ("bitrate_kbps", models.PositiveIntegerField()),
                ("size_bytes", models.PositiveBigIntegerField()),
                (
                    "checksum_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[quran_backend.modules.audio.validators.validate_sha256],
                    ),
                ),
                (
                    "object_key",
                    models.CharField(
                        max_length=512,
                        unique=True,
                        validators=[
                            quran_backend.modules.audio.validators.validate_relative_object_key
                        ],
                    ),
                ),
                (
                    "timing_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="tracks",
                        to="audio.audiotimingversion",
                    ),
                ),
                (
                    "recitation_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="audio.recitationedition",
                    ),
                ),
            ],
            options={
                "db_table": "audio_track",
                "ordering": ["scope", "surah_number", "juz_number"],
            },
        ),
        migrations.AddField(
            model_name="audiotimingversion",
            name="recitation_edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timing_versions",
                to="audio.recitationedition",
            ),
        ),
        migrations.CreateModel(
            name="Reciter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name_ar", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255)),
                ("name_ru", models.CharField(max_length=255)),
                ("biography_ar", models.TextField(blank=True)),
                ("biography_en", models.TextField(blank=True)),
                ("biography_ru", models.TextField(blank=True)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                (
                    "portrait_object_key",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        validators=[
                            quran_backend.modules.audio.validators.validate_relative_object_key
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "audio_reciter",
                "ordering": ["name_en", "code"],
                "indexes": [
                    models.Index(fields=["is_active", "name_en"], name="audio_reciter_active_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="recitationedition",
            name="reciter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recitations",
                to="audio.reciter",
            ),
        ),
        migrations.CreateModel(
            name="AyahAudioSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_ms", models.PositiveBigIntegerField()),
                ("end_ms", models.PositiveBigIntegerField()),
                (
                    "ayah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audio_segments",
                        to="quran.ayah",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="audio.audiotrack",
                    ),
                ),
            ],
            options={
                "db_table": "audio_ayah_segment",
                "ordering": ["track", "start_ms"],
                "indexes": [
                    models.Index(fields=["track", "start_ms"], name="audio_segment_timeline_idx"),
                    models.Index(fields=["ayah", "track"], name="audio_segment_ayah_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("track", "ayah"), name="audio_segment_track_ayah_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_ms__gt", models.F("start_ms"))),
                        name="audio_segment_range_valid",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="audiotrack",
            index=models.Index(
                fields=["recitation_edition", "scope", "surah_number", "juz_number"],
                name="audio_track_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="audiotrack",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("juz_number__isnull", True),
                        ("scope", "surah"),
                        ("surah_number__gte", 1),
                        ("surah_number__lte", 114),
                    ),
                    models.Q(
                        ("juz_number__gte", 1),
                        ("juz_number__lte", 30),
                        ("scope", "juz"),
                        ("surah_number__isnull", True),
                    ),
                    models.Q(
                        ("juz_number__isnull", True),
                        ("scope", "full"),
                        ("surah_number__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="audio_track_scope_target_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="audiotrack",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_ms__gt", 0)), name="audio_track_duration_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="audiotrack",
            constraint=models.CheckConstraint(
                condition=models.Q(("bitrate_kbps__gt", 0), ("bitrate_kbps__lte", 100000)),
                name="audio_track_bitrate_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="audiotrack",
            constraint=models.CheckConstraint(
                condition=models.Q(("size_bytes__gt", 0)), name="audio_track_size_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="audiotrack",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "surah")),
                fields=("recitation_edition", "surah_number"),
                name="audio_track_surah_scope_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="audiotrack",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "juz")),
                fields=("recitation_edition", "juz_number"),
                name="audio_track_juz_scope_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="audiotrack",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "full")),
                fields=("recitation_edition",),
                name="audio_track_full_scope_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="audiotimingversion",
            constraint=models.UniqueConstraint(
                fields=("recitation_edition", "version"), name="audio_timing_recitation_ver_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="recitationedition",
            index=models.Index(
                fields=["status", "quran_edition_version", "reciter"],
                name="audio_recitation_public_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recitationedition",
            index=models.Index(fields=["reciter", "status"], name="audio_recitation_reciter_idx"),
        ),
        migrations.AddConstraint(
            model_name="recitationedition",
            constraint=models.UniqueConstraint(
                fields=("code", "version"), name="audio_recitation_code_ver_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="recitationedition",
            constraint=models.UniqueConstraint(
                fields=("reciter", "quran_edition_version", "style", "version"),
                name="audio_recitation_identity_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="recitationedition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("published_at__isnull", True), ("status", "draft")),
                    models.Q(
                        ("offline_download_allowed__isnull", False),
                        ("published_at__isnull", False),
                        ("status__in", ["published", "withdrawn"]),
                        ("stream_allowed__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="audio_recitation_publication_ts",
            ),
        ),
    ]
