# Generated by Django 6.1 on 2026-08-25 18:22

import django.db.models.deletion
import quran_backend.modules.audio.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio", "0006_recitation_style_kids_repeat"),
        ("quran", "0003_quranfoundationmushaf_quranfoundationmushafsyncstate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuranFoundationAyahRecitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("environment", models.CharField(max_length=16)),
                ("source_id", models.PositiveIntegerField()),
                ("name_ar", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255)),
                ("name_ru", models.CharField(max_length=255)),
                ("style", models.CharField(blank=True, max_length=64)),
                ("audio_file_count", models.PositiveIntegerField()),
                (
                    "source_checksum_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[quran_backend.modules.audio.validators.validate_sha256],
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField()),
                (
                    "quran_edition_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quran_foundation_ayah_recitations",
                        to="quran.quraneditionversion",
                    ),
                ),
            ],
            options={
                "db_table": "audio_qf_ayah_recitation",
                "ordering": ["source_id"],
            },
        ),
        migrations.CreateModel(
            name="QuranFoundationAyahRecitationChapter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chapter_number", models.PositiveSmallIntegerField()),
                ("ayah_count", models.PositiveSmallIntegerField()),
                ("audio_files", models.JSONField(default=list)),
                (
                    "recitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="audio.quranfoundationayahrecitation",
                    ),
                ),
            ],
            options={
                "db_table": "audio_qf_ayah_recitation_chapter",
                "ordering": ["chapter_number"],
            },
        ),
        migrations.AddIndex(
            model_name="quranfoundationayahrecitation",
            index=models.Index(
                fields=["environment", "is_available", "source_id"], name="audio_qf_ayah_public_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="quranfoundationayahrecitation",
            constraint=models.UniqueConstraint(
                fields=("environment", "source_id", "quran_edition_version"),
                name="audio_qf_ayah_recitation_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="quranfoundationayahrecitation",
            constraint=models.CheckConstraint(
                condition=models.Q(("environment__in", ["prelive", "production"])),
                name="audio_qf_ayah_env_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="quranfoundationayahrecitation",
            constraint=models.CheckConstraint(
                condition=models.Q(("audio_file_count__gt", 0)), name="audio_qf_ayah_files_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="quranfoundationayahrecitationchapter",
            index=models.Index(
                fields=["recitation", "chapter_number"], name="audio_qf_ayah_chapter_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="quranfoundationayahrecitationchapter",
            constraint=models.UniqueConstraint(
                fields=("recitation", "chapter_number"), name="audio_qf_ayah_chapter_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="quranfoundationayahrecitationchapter",
            constraint=models.CheckConstraint(
                condition=models.Q(("chapter_number__gte", 1), ("chapter_number__lte", 114)),
                name="audio_qf_ayah_chapter_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="quranfoundationayahrecitationchapter",
            constraint=models.CheckConstraint(
                condition=models.Q(("ayah_count__gt", 0)), name="audio_qf_ayah_count_positive"
            ),
        ),
    ]
