# Generated by Django 6.1 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio", "0007_quran_foundation_ayah_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="reciter",
            name="biography_tr",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reciter",
            name="name_tr",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
