# Generated by Django 6.1 on 2026-09-01 01:47

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_support_turkish_locale"),
        ("audio", "0009_reciter_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioPlaybackPosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position_ms", models.PositiveBigIntegerField()),
                (
                    "speed",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.50")),
                            django.core.validators.MaxValueValidator(Decimal("2.00")),
                        ],
                    ),
                ),
                ("repeat_enabled", models.BooleanField(default=False)),
                ("range_start_ayah", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("range_end_ayah", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("client_updated_at", models.DateTimeField(db_index=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audio_playback_positions",
                        to="accounts.device",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="playback_positions",
                        to="audio.audiotrack",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_playback_position",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audio_playback_position",
                "ordering": ["user_id"],
                "indexes": [
                    models.Index(
                        fields=["user", "client_updated_at"], name="audio_playback_user_time_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("revision__gt", 0)),
                        name="audio_playback_revision_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("speed__gte", Decimal("0.50")), ("speed__lte", Decimal("2.00"))
                        ),
                        name="audio_playback_speed_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("range_end_ayah__isnull", True), ("range_start_ayah__isnull", True)
                            ),
                            models.Q(
                                ("range_end_ayah__gte", models.F("range_start_ayah")),
                                ("range_end_ayah__lte", 286),
                                ("range_start_ayah__gte", 1),
                                ("range_start_ayah__lte", 286),
                            ),
                            _connector="OR",
                        ),
                        name="audio_playback_ayah_range_valid",
                    ),
                ],
            },
        ),
    ]
