# Generated by Django 6.1 on 2026-08-09 06:50

import django.db.models.deletion
import quran_backend.modules.prayer_times.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrayerConfigRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            quran_backend.modules.prayer_times.validators.validate_version_identifier
                        ],
                    ),
                ),
                ("configuration_schema_version", models.PositiveSmallIntegerField()),
                (
                    "algorithm",
                    models.SlugField(
                        max_length=64,
                        validators=[
                            quran_backend.modules.prayer_times.validators.validate_method_code
                        ],
                    ),
                ),
                (
                    "algorithm_version",
                    models.CharField(
                        max_length=64,
                        validators=[
                            quran_backend.modules.prayer_times.validators.validate_version_identifier
                        ],
                    ),
                ),
                (
                    "timezone_database_version",
                    models.CharField(
                        max_length=64,
                        validators=[
                            quran_backend.modules.prayer_times.validators.validate_version_identifier
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "manifest_checksum_sha256",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        max_length=64,
                        validators=[quran_backend.modules.prayer_times.validators.validate_sha256],
                    ),
                ),
                ("release_notes", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                "db_table": "prayer_config_release",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "is_default", "version"], name="prayer_release_public_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("configuration_schema_version__gte", 1)),
                        name="prayer_release_schema_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("is_default", False),
                                ("manifest_checksum_sha256", ""),
                                ("published_at__isnull", True),
                                ("status", "draft"),
                                ("withdrawn_at__isnull", True),
                            ),
                            models.Q(
                                ("published_at__isnull", False),
                                ("status", "published"),
                                ("withdrawn_at__isnull", True),
                                models.Q(("manifest_checksum_sha256", ""), _negated=True),
                            ),
                            models.Q(
                                ("is_default", False),
                                ("published_at__isnull", False),
                                ("status", "withdrawn"),
                                ("withdrawn_at__isnull", False),
                                models.Q(("manifest_checksum_sha256", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="prayer_release_state_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("withdrawn_at__isnull", True),
                            ("withdrawn_at__gte", models.F("published_at")),
                            _connector="OR",
                        ),
                        name="prayer_release_withdraw_order",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True), ("status", "published")),
                        fields=("is_default",),
                        name="prayer_one_default_release",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PrayerMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        max_length=64,
                        unique=True,
                        validators=[
                            quran_backend.modules.prayer_times.validators.validate_method_code
                        ],
                    ),
                ),
                ("name_ar", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255)),
                ("name_ru", models.CharField(max_length=255)),
                ("description_ar", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("description_ru", models.TextField(blank=True)),
                ("authority_name", models.CharField(max_length=255)),
                ("authority_url", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "prayer_method",
                "ordering": ["name_en", "code"],
                "indexes": [
                    models.Index(fields=["is_active", "name_en"], name="prayer_method_active_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="PrayerMethodConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fajr_angle", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "isha_angle",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                ("isha_interval_minutes", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "ramadan_isha_interval_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("fajr_adjustment_minutes", models.SmallIntegerField(default=0)),
                ("sunrise_adjustment_minutes", models.SmallIntegerField(default=0)),
                ("dhuhr_adjustment_minutes", models.SmallIntegerField(default=0)),
                ("asr_adjustment_minutes", models.SmallIntegerField(default=0)),
                ("maghrib_adjustment_minutes", models.SmallIntegerField(default=0)),
                ("isha_adjustment_minutes", models.SmallIntegerField(default=0)),
                ("supports_middle_of_night", models.BooleanField()),
                ("supports_seventh_of_night", models.BooleanField()),
                ("supports_twilight_angle", models.BooleanField()),
                (
                    "default_high_latitude_rule",
                    models.CharField(
                        choices=[
                            ("middle_of_night", "Middle of the night"),
                            ("seventh_of_night", "Seventh of the night"),
                            ("twilight_angle", "Twilight angle"),
                        ],
                        max_length=24,
                    ),
                ),
                ("supports_polar_unresolved", models.BooleanField()),
                ("supports_polar_aqrab_balad", models.BooleanField()),
                ("supports_polar_aqrab_yaum", models.BooleanField()),
                (
                    "default_polar_resolution",
                    models.CharField(
                        choices=[
                            ("unresolved", "No polar-circle substitution"),
                            ("aqrab_balad", "Aqrab al-balad (nearest latitude)"),
                            ("aqrab_yaum", "Aqrab al-yaum (nearest day)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_name", models.CharField(max_length=255)),
                ("source_url", models.URLField()),
                ("source_version", models.CharField(max_length=128)),
                (
                    "source_checksum_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[quran_backend.modules.prayer_times.validators.validate_sha256],
                    ),
                ),
                (
                    "checksum_sha256",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        validators=[quran_backend.modules.prayer_times.validators.validate_sha256],
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configurations",
                        to="prayer_times.prayermethod",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="method_configurations",
                        to="prayer_times.prayerconfigrelease",
                    ),
                ),
            ],
            options={
                "db_table": "prayer_method_config",
                "ordering": ["release", "method__name_en", "method__code"],
                "indexes": [
                    models.Index(fields=["release", "method"], name="prayer_config_lookup_idx"),
                    models.Index(fields=["method", "release"], name="prayer_config_method_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("release", "method"), name="prayer_config_release_method_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("fajr_angle__gt", 0), ("fajr_angle__lte", 30)),
                        name="prayer_config_fajr_angle",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("isha_angle__gt", 0),
                                ("isha_angle__lte", 30),
                                ("isha_interval_minutes__isnull", True),
                                ("ramadan_isha_interval_minutes__isnull", True),
                            ),
                            models.Q(
                                ("isha_angle__isnull", True),
                                ("isha_interval_minutes__gt", 0),
                                ("isha_interval_minutes__lte", 300),
                            ),
                            _connector="OR",
                        ),
                        name="prayer_config_isha_mode",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ramadan_isha_interval_minutes__isnull", True),
                            models.Q(
                                ("isha_angle__isnull", True),
                                ("isha_interval_minutes__isnull", False),
                                ("ramadan_isha_interval_minutes__gt", 0),
                                ("ramadan_isha_interval_minutes__lte", 300),
                            ),
                            _connector="OR",
                        ),
                        name="prayer_config_ramadan_isha",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("fajr_adjustment_minutes__gte", -120),
                            ("fajr_adjustment_minutes__lte", 120),
                            ("sunrise_adjustment_minutes__gte", -120),
                            ("sunrise_adjustment_minutes__lte", 120),
                            ("dhuhr_adjustment_minutes__gte", -120),
                            ("dhuhr_adjustment_minutes__lte", 120),
                            ("asr_adjustment_minutes__gte", -120),
                            ("asr_adjustment_minutes__lte", 120),
                            ("maghrib_adjustment_minutes__gte", -120),
                            ("maghrib_adjustment_minutes__lte", 120),
                            ("isha_adjustment_minutes__gte", -120),
                            ("isha_adjustment_minutes__lte", 120),
                        ),
                        name="prayer_config_adjustments",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("default_high_latitude_rule", "middle_of_night"),
                                ("supports_middle_of_night", True),
                            ),
                            models.Q(
                                ("default_high_latitude_rule", "seventh_of_night"),
                                ("supports_seventh_of_night", True),
                            ),
                            models.Q(
                                ("default_high_latitude_rule", "twilight_angle"),
                                ("supports_twilight_angle", True),
                            ),
                            _connector="OR",
                        ),
                        name="prayer_config_hl_default_ok",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("default_polar_resolution", "unresolved"),
                                ("supports_polar_unresolved", True),
                            ),
                            models.Q(
                                ("default_polar_resolution", "aqrab_balad"),
                                ("supports_polar_aqrab_balad", True),
                            ),
                            models.Q(
                                ("default_polar_resolution", "aqrab_yaum"),
                                ("supports_polar_aqrab_yaum", True),
                            ),
                            _connector="OR",
                        ),
                        name="prayer_config_polar_default_ok",
                    ),
                ],
            },
        ),
    ]
