# Generated by Django 6.1 on 2026-08-09 07:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_refresh_sessions"),
        ("prayer_times", "0002_reference_release"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrayerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asr_method",
                    models.CharField(
                        choices=[("standard", "Standard"), ("hanafi", "Hanafi")],
                        default="standard",
                        max_length=16,
                    ),
                ),
                (
                    "high_latitude_rule",
                    models.CharField(
                        choices=[
                            ("middle_of_night", "Middle of the night"),
                            ("seventh_of_night", "Seventh of the night"),
                            ("twilight_angle", "Twilight angle"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "polar_resolution",
                    models.CharField(
                        choices=[
                            ("unresolved", "No polar-circle substitution"),
                            ("aqrab_balad", "Aqrab al-balad (nearest latitude)"),
                            ("aqrab_yaum", "Aqrab al-yaum (nearest day)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("fajr_adjustment_minutes", models.SmallIntegerField(default=0)),
                ("sunrise_adjustment_minutes", models.SmallIntegerField(default=0)),
                ("dhuhr_adjustment_minutes", models.SmallIntegerField(default=0)),
                ("asr_adjustment_minutes", models.SmallIntegerField(default=0)),
                ("maghrib_adjustment_minutes", models.SmallIntegerField(default=0)),
                ("isha_adjustment_minutes", models.SmallIntegerField(default=0)),
                (
                    "timezone_mode",
                    models.CharField(
                        choices=[("device_local", "Device local"), ("fixed", "Fixed timezone")],
                        default="device_local",
                        max_length=16,
                    ),
                ),
                ("fixed_timezone", models.CharField(blank=True, default="", max_length=255)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("client_updated_at", models.DateTimeField()),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prayer_profiles",
                        to="accounts.device",
                    ),
                ),
                (
                    "method_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profiles",
                        to="prayer_times.prayermethodconfig",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prayer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "prayer_profile",
                "indexes": [
                    models.Index(fields=["method_config"], name="prayer_profile_method_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("revision__gte", 1)),
                        name="prayer_profile_revision_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("fixed_timezone", ""), ("timezone_mode", "device_local")),
                            models.Q(
                                ("timezone_mode", "fixed"),
                                models.Q(("fixed_timezone", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="prayer_profile_timezone_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("fajr_adjustment_minutes__gte", -120),
                            ("fajr_adjustment_minutes__lte", 120),
                            ("sunrise_adjustment_minutes__gte", -120),
                            ("sunrise_adjustment_minutes__lte", 120),
                            ("dhuhr_adjustment_minutes__gte", -120),
                            ("dhuhr_adjustment_minutes__lte", 120),
                            ("asr_adjustment_minutes__gte", -120),
                            ("asr_adjustment_minutes__lte", 120),
                            ("maghrib_adjustment_minutes__gte", -120),
                            ("maghrib_adjustment_minutes__lte", 120),
                            ("isha_adjustment_minutes__gte", -120),
                            ("isha_adjustment_minutes__lte", 120),
                        ),
                        name="prayer_profile_adjustments",
                    ),
                ],
            },
        ),
    ]
