from __future__ import annotations

# Russian interface strings intentionally contain characters that resemble Latin glyphs.
# ruff: noqa: RUF001
from django.contrib import admin
from django.utils.translation import gettext_lazy

MODEL_LABELS: dict[str, tuple[str, str]] = {
    "accounts.User": ("пользователь", "пользователи"),
    "accounts.AuthIdentity": ("способ входа", "способы входа"),
    "accounts.Device": ("устройство", "устройства"),
    "accounts.RefreshSession": ("сессия входа", "сессии входа"),
    "accounts.RefreshToken": ("токен обновления", "токены обновления"),
    "accounts.Consent": ("согласие", "согласия"),
    "accounts.EmailAuthChallenge": ("код входа по email", "коды входа по email"),
    "accounts.GuestMergeAudit": (
        "перенос гостевых данных",
        "история переноса гостевых данных",
    ),
    "quran.QuranEdition": ("издание Корана", "издания Корана"),
    "quran.QuranEditionVersion": ("версия издания", "версии изданий"),
    "quran.Surah": ("сура", "суры"),
    "quran.Ayah": ("аят", "аяты"),
    "quran.MushafPage": ("страница Мусхафа", "страницы Мусхафа"),
    "quran.AyahPageRegion": ("область аята", "области аятов на страницах"),
    "quran.Juz": ("джуз", "джузы"),
    "quran.Hizb": ("хизб", "хизбы"),
    "quran.RubElHizb": ("руб аль-хизб", "рубы аль-хизб"),
    "quran.SourceManifest": ("манифест источника", "манифесты источников"),
    "quran.QuranFoundationMushafSyncState": (
        "состояние синхронизации мусхафов",
        "синхронизация мусхафов Quran.Foundation",
    ),
    "quran.QuranFoundationMushaf": (
        "мусхаф Quran.Foundation",
        "мусхафы Quran.Foundation",
    ),
    "quran.QuranFoundationMushafPage": (
        "страница мусхафа Quran.Foundation",
        "страницы мусхафов Quran.Foundation",
    ),
    "quran.QuranFoundationNativePublication": (
        "нативная публикация мусхафа",
        "нативные публикации мусхафов Quran.Foundation",
    ),
    "quran.QuranFoundationNativePageAsset": (
        "нативное изображение страницы",
        "нативные изображения страниц мусхафа",
    ),
    "translations.TranslationEdition": (
        "смысловой перевод Корана",
        "смысловые переводы Корана",
    ),
    "translations.TranslationEditionVersion": (
        "версия смыслового перевода",
        "версии смысловых переводов",
    ),
    "translations.AyahTranslation": (
        "перевод аята",
        "переводы аятов",
    ),
    "translations.QuranFoundationTranslationSyncState": (
        "состояние синхронизации переводов",
        "синхронизация переводов Quran.Foundation",
    ),
    "tafsirs.TafsirEdition": ("Тафсир Корана", "Тафсиры Корана"),
    "tafsirs.TafsirEditionVersion": ("версия Тафсира", "версии Тафсиров"),
    "tafsirs.AyahTafsir": ("Тафсир аята", "Тафсиры аятов"),
    "tafsirs.QuranFoundationTafsirSyncState": (
        "состояние синхронизации Тафсиров",
        "синхронизация Тафсиров Quran.Foundation",
    ),
    "audio.QuranFoundationAyahRecitation": (
        "чтение по аятам Quran.Foundation",
        "чтения по аятам Quran.Foundation",
    ),
    "audio.QuranFoundationAyahRecitationChapter": (
        "сура в чтении Quran.Foundation",
        "суры в чтениях Quran.Foundation",
    ),
    "audio.QuranFoundationSyncState": (
        "состояние синхронизации аудио",
        "синхронизация аудио Quran.Foundation",
    ),
    "audio.Reciter": ("чтец", "чтецы"),
    "audio.RecitationEdition": ("вариант чтения", "варианты чтения"),
    "audio.AudioTimingVersion": ("версия таймкодов", "версии таймкодов"),
    "audio.AudioTrack": ("аудиодорожка", "аудиодорожки"),
    "audio.AudioRendition": ("аудиофайл", "аудиофайлы"),
    "audio.AyahAudioSegment": ("таймкод аята", "таймкоды аятов"),
    "prayer_times.PrayerMethod": ("метод расчёта", "методы расчёта намаза"),
    "prayer_times.PrayerConfigRelease": (
        "выпуск настроек",
        "выпуски настроек намаза",
    ),
    "prayer_times.PrayerMethodConfig": (
        "настройка метода",
        "настройки методов расчёта",
    ),
    "prayer_times.PrayerProfile": (
        "профиль расчёта намаза",
        "профили расчёта намаза",
    ),
    "reminders.ReminderRule": ("правило напоминания", "правила напоминаний"),
    "reminders.RetiredReminderId": (
        "удалённое напоминание",
        "идентификаторы удалённых напоминаний",
    ),
    "feedback.FeedbackTicket": ("обращение", "обращения пользователей"),
    "feedback.FeedbackMessage": ("сообщение", "сообщения по обращениям"),
    "feedback.FeedbackAudit": ("изменение обращения", "история изменений обращений"),
    "feedback.FeedbackContext": ("контекст обращения", "контекст обращений"),
    "website.SocialProfile": ("социальная сеть", "социальные сети"),
    "share_referrals.ShareCampaign": (
        "кампания «Поделиться приложением»",
        "1. Кампании «Поделиться приложением»",
    ),
    "share_referrals.ReferralLink": (
        "персональная ссылка пользователя",
        "2. Персональные ссылки и промокоды",
    ),
    "share_referrals.ShareEvent": (
        "действие пользователя в разделе приглашений",
        "Статистика действий «Поделиться»",
    ),
    "share_referrals.ReferralClick": (
        "переход по короткой ссылке",
        "Статистика переходов по ссылкам",
    ),
    "share_referrals.ReferralAttribution": (
        "подтверждение приглашения",
        "3. Приглашения пользователей",
    ),
    "share_referrals.ReferralQualification": (
        "проверка условий приглашения",
        "4. Проверка условий приглашений",
    ),
    "share_referrals.ReferralReward": (
        "бонус за приглашение",
        "5. Бонусы за приглашения",
    ),
    "share_referrals.ReferralRewardAudit": (
        "запись истории бонуса",
        "История операций с бонусами",
    ),
    "dua.DuaCollection": ("сборник ду’а", "сборники ду’а"),
    "dua.DuaCollectionVersion": ("версия сборника ду’а", "версии сборников ду’а"),
    "dua.DuaSourceEdition": ("издание-источник ду’а", "издания-источники ду’а"),
    "dua.DuaCategory": ("раздел ду’а", "разделы ду’а"),
    "dua.DuaCategoryTranslation": ("перевод раздела ду’а", "переводы разделов ду’а"),
    "dua.DuaEntry": ("ду’а", "ду’а"),
    "dua.DuaEntryTranslation": ("перевод ду’а", "переводы ду’а"),
    "dua.DuaEvidence": ("ссылка на источник ду’а", "ссылки на источники ду’а"),
    "dua.DuaAudioAsset": ("аудиозапись ду’а", "аудиозаписи ду’а"),
    "dua.DuaFavorite": ("избранная ду’а", "избранные ду’а"),
}


FIELD_LABELS: dict[str, str] = {
    "account_mode": "Тип аккаунта",
    "android_url": "Ссылка Google Play",
    "approved_at": "Одобрено",
    "approved_by": "Одобрил",
    "attributed_at": "Дата атрибуции",
    "beneficiary": "Получатель",
    "campaign": "Кампания",
    "canonical_download_url": "Основная страница загрузки",
    "client_event_id": "ID события клиента",
    "config_version": "Версия конфигурации",
    "created_by": "Создал",
    "decided_at": "Решение принято",
    "decided_by": "Решение принял",
    "decision_reason": "Основание решения",
    "disabled_at": "Отключено",
    "disabled_by": "Отключил",
    "ends_at": "Окончание",
    "internal_name": "Название для команды",
    "invitee": "Приглашённый аккаунт",
    "ios_url": "Ссылка App Store",
    "key": "Стабильный ключ",
    "metadata": "Безопасные метаданные",
    "new_status": "Новый статус",
    "occurred_at": "Произошло на клиенте",
    "owner": "Владелец",
    "points": "Баллы",
    "prepared_pages": "Подготовлено страниц",
    "previous_status": "Предыдущий статус",
    "publication": "Публикация",
    "qualification": "Квалификация",
    "received_at": "Получено сервером",
    "render_version": "Версия рендера",
    "renderer_name": "Рендерер",
    "renderer_version": "Версия рендерера",
    "referral_enabled": "Рефералы включены",
    "referral_link": "Реферальная ссылка",
    "result": "Результат",
    "required_widths": "Требуемые ширины",
    "reversal_reason": "Причина отмены",
    "reversed_at": "Отменено",
    "reversed_by": "Отменил",
    "revoked_by": "Отозвал",
    "reward": "Начисление",
    "reward_points": "Баллов за приглашение",
    "short_link_base_url": "База коротких ссылок",
    "source": "Источник",
    "starts_at": "Начало",
    "state_reason": "Причина состояния",
    "storage_key": "Ключ в хранилище",
    "action": "Действие",
    "active_version": "Активная версия",
    "actor": "Исполнитель",
    "actor_type": "Тип исполнителя",
    "ad_campaign_id": "ID рекламной кампании",
    "ad_creative_id": "ID рекламного материала",
    "algorithm": "Алгоритм",
    "algorithm_version": "Версия алгоритма",
    "app_build": "Сборка приложения",
    "app_version": "Версия приложения",
    "asr_adjustment_minutes": "Поправка Асра, минуты",
    "asr_method": "Метод расчёта Асра",
    "asset_variants": "Варианты файла",
    "assets_count": "Количество файлов",
    "arabic_text": "Арабский текст",
    "assignee": "Ответственный",
    "attempts_remaining": "Осталось попыток",
    "audio_file_count": "Количество аудиофайлов",
    "audio_files": "Аудиофайлы",
    "audio_track_id": "ID аудиодорожки",
    "author": "Автор",
    "author_name": "Имя автора",
    "author_type": "Тип автора",
    "authority_name": "Расчётная организация",
    "authority_url": "Сайт расчётной организации",
    "ayah": "Аят",
    "ayah_count": "Количество аятов",
    "ayah_number": "Номер аята",
    "attribution": "Атрибуция",
    "biography_ar": "Биография на арабском",
    "biography_en": "Биография на английском",
    "biography_ru": "Биография на русском",
    "biography_tr": "Биография на турецком",
    "profile_source_checked_on": "Источник проверен",
    "profile_source_url": "Публичный источник данных",
    "bitrate_kbps": "Битрейт, кбит/с",
    "body": "Текст сообщения",
    "bootstrap_generation": "Поколение регистрации",
    "category": "Категория",
    "category_count": "Количество разделов",
    "cdn_contract_verified_at": "Проверка CDN-контракта",
    "channel": "Канал",
    "chapter_number": "Номер суры",
    "checksum_sha256": "Контрольная сумма SHA-256",
    "client_message_id": "ID сообщения клиента",
    "client_platform": "Платформа клиента",
    "client_request_id": "ID запроса клиента",
    "client_updated_at": "Изменено на устройстве",
    "closed_at": "Закрыто",
    "code": "Код",
    "code_hash": "Хеш кода",
    "codec": "Кодек",
    "completed_at": "Завершено",
    "collection": "Сборник",
    "collection_version": "Версия сборника",
    "compromise_detected_at": "Обнаружена компрометация",
    "configuration_schema_version": "Версия схемы настроек",
    "consecutive_failures": "Ошибок подряд",
    "consumed_at": "Использовано",
    "contact_email": "Контактный email",
    "content_sync_resource_id": "ID ресурса синхронизации",
    "content_type": "Тип содержимого",
    "content_version": "Версия содержимого",
    "covered_ayah_count": "Количество охваченных аятов",
    "country_code": "Код страны",
    "created_at": "Создано",
    "date_joined": "Дата регистрации",
    "default_font_name": "Шрифт по умолчанию",
    "default_high_latitude_rule": "Правило высоких широт по умолчанию",
    "default_polar_resolution": "Полярная поправка по умолчанию",
    "deleted_at": "Удалено",
    "deletion_requested_at": "Запрошено удаление",
    "deletion_scheduled_for": "Удаление запланировано на",
    "delivery_mode": "Способ доставки",
    "description": "Описание",
    "description_ar": "Описание на арабском",
    "description_en": "Описание на английском",
    "description_ru": "Описание на русском",
    "device": "Устройство",
    "dhuhr_adjustment_minutes": "Поправка Зухра, минуты",
    "duration_ms": "Продолжительность, мс",
    "edition": "Издание",
    "edition_code": "Код издания",
    "edition_version": "Версия издания",
    "email": "Email",
    "email_at_provider": "Email у провайдера",
    "email_verified": "Email подтверждён",
    "end_ayah": "Конечный аят",
    "end_ayah_number": "Номер конечного аята",
    "end_ms": "Конец, мс",
    "end_surah_number": "Номер конечной суры",
    "end_verse_id": "ID конечного аята у источника",
    "end_verse_key": "Координата конечного аята",
    "entry": "Ду’а",
    "entry_count": "Количество ду’а",
    "environment": "Среда",
    "etag": "ETag",
    "expected_ayahs": "Ожидается аятов",
    "expected_pages": "Ожидается страниц",
    "expected_surahs": "Ожидается сур",
    "expires_at": "Истекает",
    "external_url": "Внешний URL",
    "external_id": "ID у внешнего источника",
    "fajr_adjustment_minutes": "Поправка Фаджра, минуты",
    "fajr_angle": "Угол Фаджра",
    "first_response_at": "Первый ответ",
    "first_verse_id": "ID первого аята",
    "first_word_id": "ID первого слова",
    "fixed_timezone": "Фиксированный часовой пояс",
    "granted_at": "Согласие дано",
    "group_verses_count": "Количество аятов в группе",
    "grade": "Степень достоверности",
    "height": "Высота",
    "high_latitude_rule": "Правило высоких широт",
    "hizb": "Хизб",
    "hizb_count": "Количество хизбов",
    "hizb_number": "Номер хизба",
    "id": "ID",
    "idempotency_key": "Ключ идемпотентности",
    "image_height": "Высота изображения",
    "image_width": "Ширина изображения",
    "imported_at": "Импортировано",
    "installation_credential_hash": "Хеш ключа установки",
    "installation_id_hash": "Хеш ID установки",
    "invalidated_at": "Аннулировано",
    "is_active": "Активен",
    "is_available": "Доступен",
    "is_default": "По умолчанию",
    "is_enabled": "Включено",
    "include_in_seo": "Добавлять в SEO",
    "is_staff": "Доступ в админку",
    "is_superuser": "Суперпользователь",
    "isha_adjustment_minutes": "Поправка Иша, минуты",
    "isha_angle": "Угол Иша",
    "isha_interval_minutes": "Интервал Иша, минуты",
    "juz_count": "Количество джузов",
    "juz_number": "Номер джуза",
    "kind": "Тип ссылки",
    "last_attempt_at": "Последняя попытка",
    "last_change_at": "Последнее изменение",
    "last_error_code": "Код последней ошибки",
    "last_error_message": "Описание последней ошибки",
    "last_login": "Последний вход",
    "last_public_message_at": "Последнее публичное сообщение",
    "last_revision": "Последняя редакция",
    "last_seen_at": "Последняя активность",
    "last_success_at": "Последняя успешная синхронизация",
    "last_sync_sequence": "Последний номер синхронизации",
    "last_synced_at": "Синхронизировано",
    "last_used_at": "Последнее использование",
    "last_verse_id": "ID последнего аята",
    "last_word_id": "ID последнего слова",
    "license_attribution": "Текст атрибуции лицензии",
    "license_name": "Лицензия",
    "license_spdx_id": "SPDX ID лицензии",
    "license_url": "URL лицензии",
    "language_code": "Код языка",
    "language_name": "Название языка",
    "lines_per_page": "Строк на странице",
    "linked_at": "Подключено",
    "local_time": "Местное время",
    "locale": "Язык",
    "maghrib_adjustment_minutes": "Поправка Магриба, минуты",
    "manifest_checksum_sha256": "Контрольная сумма манифеста SHA-256",
    "mapping_mode": "Способ разметки",
    "method": "Метод расчёта",
    "method_config": "Настройка метода",
    "meaning_text": "Смысл",
    "moved_counts": "Перенесённые данные",
    "mushaf": "Мусхаф",
    "name": "Название",
    "name_ar": "Название на арабском",
    "name_en": "Название на английском",
    "name_ru": "Название на русском",
    "name_tr": "Название на турецком",
    "new_values": "Новые значения",
    "number": "Номер",
    "object_key": "Ключ объекта",
    "offline_download_allowed": "Разрешено скачивание",
    "old_values": "Предыдущие значения",
    "origin_etag": "Исходный ETag",
    "os_version": "Версия ОС",
    "page": "Страница",
    "page_count": "Количество страниц",
    "page_number": "Номер страницы",
    "pages_count": "Количество страниц",
    "password": "Пароль",
    "payload": "Данные",
    "platform": "Платформа",
    "profile_url": "Ссылка на профиль",
    "playback_ms": "Позиция воспроизведения, мс",
    "polar_resolution": "Полярная поправка",
    "policy_version": "Версия политики",
    "polygon": "Полигон",
    "portrait_object_key": "Ключ портрета",
    "prayer_event": "Намаз",
    "prayer_offset_minutes": "Смещение от намаза, минуты",
    "preferred_locale": "Предпочитаемый язык",
    "priority": "Приоритет",
    "provider": "Провайдер входа",
    "provider_group_id": "ID группы у провайдера",
    "provider_subject": "ID у провайдера",
    "public_id": "Номер обращения",
    "published_at": "Опубликовано",
    "purpose": "Назначение",
    "qirat_id": "ID кираата",
    "qirat_name": "Кираат",
    "quality": "Качество",
    "quran_edition_version": "Версия издания Корана",
    "ramadan_isha_interval_minutes": "Интервал Иша в Рамадан, минуты",
    "reading_order": "Порядок чтения",
    "reader_name": "Имя чтеца",
    "reader_name_ar": "Имя чтеца на арабском",
    "reason": "Причина",
    "record_count": "Количество записей",
    "recitation": "Чтение",
    "recitation_edition": "Вариант чтения",
    "recitation_id": "ID чтения",
    "reciter": "Чтец",
    "reciter_id": "ID чтеца",
    "release": "Выпуск настроек",
    "release_notes": "Примечания к выпуску",
    "reminder_id": "ID напоминания",
    "reminder_type": "Тип напоминания",
    "reopen_count": "Количество повторных открытий",
    "reopened_at": "Повторно открыто",
    "replaced_by": "Заменено на",
    "reporter": "Автор обращения",
    "request_fingerprint": "Отпечаток запроса",
    "repetitions": "Количество повторений",
    "repetition_label": "Схема повторений",
    "requester": "Инициатор входа",
    "resolved_at": "Решено",
    "resource_content_id": "ID содержимого ресурса",
    "resources_filter": "Фильтр ресурсов",
    "result_user": "Пользователь после входа",
    "retired_at": "Удалено",
    "revelation_type": "Место ниспослания",
    "revision": "Редакция",
    "reviewer": "Проверяющий редактор",
    "revoked_at": "Отозвано",
    "rights_holder": "Правообладатель",
    "rights_url": "Условия использования",
    "riwayah": "Риваят",
    "route": "Страница приложения",
    "rub_el_hizb_count": "Количество четвертей хизба",
    "rub_el_hizb_number": "Номер четверти хизба",
    "schema_version": "Версия схемы",
    "scope": "Охват",
    "secret_hash": "Хеш секрета",
    "session": "Сессия",
    "signal": "Сигнал",
    "size_bytes": "Размер, байты",
    "slug": "Слаг",
    "sla_response_due_at": "Срок ответа по SLA",
    "source_checksum_sha256": "Контрольная сумма источника SHA-256",
    "source_id": "ID источника",
    "source_item_id": "ID материала у источника",
    "source_name": "Источник",
    "source_number": "Номер в источнике",
    "source_reference": "Библиографическая ссылка",
    "source_reciter_id": "ID чтеца у источника",
    "source_url": "URL источника",
    "source_user": "Гостевой пользователь",
    "source_text": "Исходный текст",
    "source_version": "Версия источника",
    "sort_order": "Порядок вывода",
    "start_ayah": "Начальный аят",
    "start_ayah_number": "Номер начального аята",
    "start_ms": "Начало, мс",
    "start_surah_number": "Номер начальной суры",
    "start_verse_id": "ID начального аята у источника",
    "start_verse_key": "Координата начального аята",
    "status": "Статус",
    "stream_allowed": "Разрешено потоковое воспроизведение",
    "style": "Стиль чтения",
    "subject": "Тема",
    "text": "Текст",
    "title": "Название",
    "translator": "Переводчик",
    "transliteration": "Транслитерация",
    "foot_notes": "Сноски",
    "sunrise_adjustment_minutes": "Поправка восхода, минуты",
    "supports_middle_of_night": "Поддерживает середину ночи",
    "supports_polar_aqrab_balad": "Поддерживает акраб аль-балад",
    "supports_polar_aqrab_yaum": "Поддерживает акраб аль-яум",
    "supports_polar_unresolved": "Допускает отсутствие полярной поправки",
    "supports_seventh_of_night": "Поддерживает седьмую часть ночи",
    "supports_twilight_angle": "Поддерживает угол сумерек",
    "surah": "Сура",
    "surah_count": "Количество сур",
    "surah_number": "Номер суры",
    "sync_sequence": "Номер синхронизации",
    "sync_token": "Токен синхронизации",
    "target_user": "Основной пользователь",
    "team": "Команда",
    "text_search": "Текст для поиска",
    "text_uthmani": "Текст Усмани",
    "display_name": "Название аккаунта",
    "ticket": "Обращение",
    "timezone": "Часовой пояс",
    "timezone_database_version": "Версия базы часовых поясов",
    "timezone_mode": "Режим часового пояса",
    "timezone_name": "Часовой пояс",
    "timing_version": "Версия таймкодов",
    "track": "Аудиодорожка",
    "trigger_identity": "Способ входа, запустивший перенос",
    "updated_at": "Изменено",
    "url": "URL",
    "used_at": "Использовано",
    "user": "Пользователь",
    "verification_key": "Ключ подтверждения",
    "verified_at": "Проверено",
    "verification_status": "Статус проверки",
    "verse_mapping": "Привязка аятов",
    "verse_key": "Координата аята",
    "verses_count": "Количество аятов",
    "version": "Версия",
    "visibility": "Видимость",
    "weekdays_mask": "Дни недели",
    "width": "Ширина",
    "withdrawn_at": "Отозвано",
    "words": "Слова и координаты",
    "x": "Координата X",
    "y": "Координата Y",
}


def configure_russian_admin() -> None:
    """Apply operator-facing Russian labels without changing database schema."""

    admin.site.site_header = "Администрирование Iqro"
    admin.site.site_title = "Админ-панель Iqro"
    admin.site.index_title = "Управление платформой"

    for model in admin.site._registry:
        labels = MODEL_LABELS.get(model._meta.label)
        if labels is not None:
            model._meta.verbose_name, model._meta.verbose_name_plural = labels

        for field in model._meta.fields:
            translated_label = FIELD_LABELS.get(field.name)
            if translated_label is not None:
                field.verbose_name = translated_label

            if field.choices:
                field.choices = [
                    (value, gettext_lazy(str(label))) for value, label in field.choices
                ]
