# Generated by Django 6.1 on 2026-08-28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuranFoundationTranslationSyncState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("environment", models.CharField(max_length=16)),
                ("resources_filter", models.CharField(max_length=255)),
                ("sync_token", models.TextField(blank=True)),
                ("last_sync_sequence", models.PositiveBigIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
            ],
            options={"db_table": "translation_qf_sync_state"},
        ),
        migrations.CreateModel(
            name="TranslationEdition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("environment", models.CharField(max_length=16)),
                ("provider", models.CharField(default="quran_foundation", max_length=32)),
                ("source_id", models.PositiveIntegerField()),
                ("slug", models.SlugField(max_length=128)),
                ("language_code", models.CharField(db_index=True, max_length=8)),
                ("language_name", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("author_name", models.CharField(max_length=255)),
                ("source_name", models.CharField(max_length=255)),
                ("source_url", models.URLField()),
                ("license_name", models.CharField(max_length=255)),
                ("license_url", models.URLField()),
                ("attribution", models.CharField(max_length=500)),
                ("is_available", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "translation_edition",
                "ordering": ["language_code", "name", "source_id"],
            },
        ),
        migrations.CreateModel(
            name="TranslationEditionVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sync_sequence", models.PositiveBigIntegerField()),
                ("schema_version", models.CharField(max_length=32)),
                ("checksum_sha256", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("ayah_count", models.PositiveSmallIntegerField()),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="translations.translationedition",
                    ),
                ),
            ],
            options={
                "db_table": "translation_edition_version",
                "ordering": ["-sync_sequence"],
            },
        ),
        migrations.AddField(
            model_name="translationedition",
            name="active_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_editions",
                to="translations.translationeditionversion",
            ),
        ),
        migrations.CreateModel(
            name="AyahTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_id", models.PositiveBigIntegerField()),
                ("verse_key", models.CharField(max_length=16)),
                ("surah_number", models.PositiveSmallIntegerField()),
                ("ayah_number", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                ("source_text", models.TextField()),
                ("foot_notes", models.JSONField(default=list)),
                (
                    "edition_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ayah_translations",
                        to="translations.translationeditionversion",
                    ),
                ),
            ],
            options={
                "db_table": "translation_ayah",
                "ordering": ["surah_number", "ayah_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="quranfoundationtranslationsyncstate",
            constraint=models.UniqueConstraint(
                fields=("environment", "resources_filter"), name="translation_qf_sync_state_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="translationedition",
            constraint=models.UniqueConstraint(
                fields=("environment", "provider", "source_id"),
                name="translation_edition_provider_source_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="translationeditionversion",
            constraint=models.UniqueConstraint(
                fields=("edition", "sync_sequence"), name="translation_version_sequence_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="translationeditionversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("ayah_count__gt", 0)),
                name="translation_version_positive_ayah_count",
            ),
        ),
        migrations.AddConstraint(
            model_name="translationeditionversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("published_at__isnull", False), ("status", "published")),
                    models.Q(("status", "published"), _negated=True),
                    _connector="OR",
                ),
                name="translation_published_version_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="ayahtranslation",
            constraint=models.UniqueConstraint(
                fields=("edition_version", "verse_key"), name="translation_ayah_version_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="ayahtranslation",
            constraint=models.CheckConstraint(
                condition=models.Q(("surah_number__gte", 1), ("surah_number__lte", 114)),
                name="translation_ayah_surah_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="ayahtranslation",
            constraint=models.CheckConstraint(
                condition=models.Q(("ayah_number__gte", 1)), name="translation_ayah_number_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="ayahtranslation",
            index=models.Index(
                fields=["edition_version", "surah_number", "ayah_number"],
                name="translation_ayah_lookup_idx",
            ),
        ),
    ]
