import type { PrototypeState } from "./types";

export const initialState: PrototypeState = {
  route: "onboarding-language",
  previousRoute: "home",
  onboarded: false,
  locale: "ru",
  theme: "light",
  goal: "reading",
  dailyUnit: "pages",
  dailyTarget: 6,
  dailyAchieved: 2,
  readerMode: "text",
  mushafId: 5,
  mushafZoom: 1,
  selectedAyah: 1,
  lastPosition: { surah: 1, ayah: 1, page: 1 },
  quranBookmarks: [],
  duaFavorites: [],
  selectedDua: 1,
  selectedReciter: "alafasy",
  player: {
    active: false,
    playing: false,
    reciterId: "alafasy",
    surah: 1,
    ayah: 1,
    progress: 18,
    repeat: "off",
    speed: 1,
    pauseSeconds: 2,
  },
  prayerPages: { fajr: 0, dhuhr: 1, asr: 0, maghrib: 1, isha: 0 },
  prayerNotifications: { fajr: false, dhuhr: false, asr: false, maghrib: false, isha: false },
  afterPrayerPrompt: false,
  memorization: {
    startAyah: 1,
    endAyah: 3,
    targetRepetitions: 5,
    completedRepetitions: 0,
    pauseSeconds: 2,
    assessment: "",
  },
  systemState: "online",
  accountMode: "guest",
  toast: "",
  modal: "",
};
